### ISSUE TITLE
logout after 60 seconds

### ISSUE THREAD

**Issue by Nemofly** [fcturner/passwords#103]
Hey, i use your App 16.2 in my OC 8.2.1 with Firefox 42.0.
Normally the automated Logout time is 60 secounds. If I go to personalize and change the seconds maybe to 600, the app shows me 10 Minutes right down. But after 60 seconds it locks me out.
So the time I set by myself do not work.
Maybe you can fix it?
If you have any further questions please ask me :-)
Thanks

**Comment by fcturner** [comment]
Can you tell me the text of your message?
Is it either
`You will be logged off due to expiration of your session cookie (set to 1 minutes).`
or is it
`You will be logged off due to inactivity of 60 seconds.`
??

**Comment by fcturner** [comment]
What does the output of this query tell you?
```sql
SELECT * FROM oc_preferences WHERE appid = 'passwords' AND configkey = 'timer'
```
It should show a value of 60 in your username's record.

**Comment by Nemofly** [comment]
Hi this is the text:
You will be logged off due to inactivity of 60 seconds.

Von meinem iPhone gesendet

> Am 24.11.2015 um 09:21 schrieb Fallon Turner <notifications@github.com>:
> 
> You will be logged off due to inactivity of 60 seconds.

**Comment by Nemofly** [comment]
Yes it is shown 60 in configvalue.
But i would habe 600 in my profile.


Von meinem iPhone gesendet

> Am 24.11.2015 um 09:25 schrieb Fallon Turner <notifications@github.com>:
> 
> SELECT * FROM oc_preferences WHERE appid = 'passwords' AND configkey = 'timer'

**Comment by icebrian** [comment]
I have a similar problem, however, my timeout occurs after 30 seconds, always. I am running ownCloud 8.0.4 on a QNAP.

I have set timeout to 300 seconds and have also verified that in database it it set to 300, however I get a message at 30 seconds and also logged out.

**Comment by icebrian** [comment]
Just noticed something. It seems this only happens after I hoover my mouse over a password.

So, if I open "Passwords" and don't do anything, the counter, counts down correctly. If I click somewhere, move the  mouse around and hoover over a password (to make it visible), I will then be logged out after about 30seconds.

**Comment by fcturner** [comment]
Hmm, so it doesn't reset correctly. Thanks, I will try to kill this bug.

**Comment by pawiecki** [comment]
Hello! I have the same problem on latest owncloud server and passwords app on debian - both downloaded and installed today, 3 february. But mine says:

You will be logged off due to expiration of your session cookie (set to 60 minutes).

I just installed it and tried to add password, but the error happened. I haven't touched the config. I really like the app, and the functionality it gives, very handy. Thanks :)

**Comment by viki53** [comment]
Hi, same here.

Need a hand fixing it?

**Comment by fcturner** [comment]
Thanks, that's sweet. But I think I got it. Version 17 will contain the fix, to be released this weekend I hope.

**Comment by fcturner** [comment]
Almost done with v17! I'm sorry that it takes some more time.

**Comment by icebrian** [comment]
Just tested version 17. Timeout clock seems to be working just fine, meaning countdown's correctly, however, logging out seems to have a problem. After the 60 seconds I get the notification window, saying I will be logged out, after I press OK, the password list disappears, but I am not logged out of ownCloud's interface. If I navigate away to the Files page and back to the Password page, I can once again see the passwords.

**Comment by fcturner** [comment]
Great! The behaviour is perfectly normal. I disabled the one line of code that actually logs you off, when I was working on this. If you see the alert, the new code works. Just need to uncomment the line before the release. 

Thanks for testing!

**Comment by icebrian** [comment]
No problem! Thank you for your great work! :)

**Comment by fcturner** [comment]
Implemented and released: [v17](https://github.com/fcturner/passwords/releases/tag/17).
