### ISSUE TITLE
Confirmation doesn't work on delete single password in trash

### ISSUE THREAD

**Issue by Nemofly** [fcturner/passwords#104]
Hey, i use your App 16.2 in OC 8.2.1 with firefox 42.0.
I deleted a password. So it goes in the trashbin folder. That works great.
If I go to the trashbin and click on delete the password. While the popup appears to ask you to be sure to delete the password, the password is still deletet in the background. In the popup i can click yes or no, but the funktion does not work. i only can click on the X so the popup closes. But the password in the trashbin is away. Even if i delete it unintentionally.
So please first delete it if i clicked on yes.
Please fix this.
Thanks

**Comment by fcturner** [comment]
Fixed in #109
