### ISSUE TITLE
Errors in translation

### ISSUE THREAD

**Issue by 8l4ckSh33p** [fcturner/passwords#110]
See screenshot:
![password](https://cloud.githubusercontent.com/assets/8858878/11957220/b6e199c8-a8c0-11e5-8b73-fe94c77ba228.png)
![password2](https://cloud.githubusercontent.com/assets/8858878/11957221/b70c74ea-a8c0-11e5-885c-c69cd1ba2d4f.png)
Please upload a translation template.

**Comment by IzK666** [comment]
https://raw.githubusercontent.com/fcturner/passwords/master/TRANSLATION.js

**Comment by fcturner** [comment]
Merged via #111 and #112
