### ISSUE TITLE
Enhancement: Auto Logout for all of owncloud

### ISSUE THREAD

**Issue by jmicks8** [fcturner/passwords#116]
Thanks for all of your work developing and maintaining this app. I like the addition of the auto logout widget in the bottom of the screen and I think that this type of functionality is missing from the owncloud core. is it possible to expand this function to the rest of the owncloud install/apps?

**Comment by fcturner** [comment]
Hello!

That can only be done using another app (my code is open-source...), or [requesting it on the ownCloud core repository](https://github.com/owncloud/core/issues/new/). It is outside the scope of this passwords app, but I really like the idea!
