### ISSUE TITLE
Translate Passwords app with Transifex

### ISSUE THREAD

**Issue by fcturner** [fcturner/passwords#117]
Dear Thomas (@DeepDiver1975),

As the developer of this app, I would really like to have this app translated using Transifex. I asked pellaeon ([apps.owncloud.com](https://apps.owncloud.com/usermanager/search.php?username=pellaeon), [github](https://github.com/pellaeon)) on apps.owncloud.org how he did it with [his registration app](https://github.com/pellaeon/registration) and he told me that you helped him out. Would you please help me out too? I saw [the directory owncloud/core/l10n](https://github.com/owncloud/core/tree/master/l10n), but don't know how to set it up without the proper files.

My strings are all in [TRANSLATION.js](https://github.com/fcturner/passwords/blob/master/TRANSLATION.js).

Many thanks!

**Comment by fcturner** [comment]
Dear ownCloud developers, 

Is there someone who will please help me out?
@LukasReschke, @DeepDiver1975

**Comment by DeepDiver1975** [comment]
Please add the user owncloud-bot to the contributors of this repo - write access required.
I'll setup a transifex job for you on our jenkins server to sync translations

**Comment by fcturner** [comment]
Many thanks!!!

**Comment by DeepDiver1975** [comment]
the job is there - https://ci.owncloud.org/view/translation-sync/job/translation-sync-passwords/

**Comment by DeepDiver1975** [comment]
on transifex: https://www.transifex.com/owncloud-org/owncloud/passwords/

**Comment by DeepDiver1975** [comment]
Access works - https://github.com/fcturner/passwords/commit/0df78dc1913d7b09b9eb5d08bb4f841f70bcefa2

**Comment by DeepDiver1975** [comment]
Translations will flow into the repo on a daily basis -> close

have fun! :wink:

**Comment by fcturner** [comment]
Great great great!!
