### ISSUE TITLE
Copy-Button for every password

### ISSUE THREAD

**Issue by tmaex** [fcturner/passwords#119]
Since hovering and Ctrl+C does'nt work in FF (at least for me) a button for copying the password to your clipboard would be nice.

I would place it left of the trash bin icon or left of website column. This way the password even won't be shown while copying it.

**Comment by fcturner** [comment]
I implemented this, for release of v17. Will be around next week.

**Comment by fcturner** [comment]
Almost done with v17! I'm sorry that it takes some more time.

**Comment by tmaex** [comment]
Hey, this is how open-source software works:
Free stuff - no complaints

Thanks for your time and the info!
If you need a hand, anytime.

**Comment by fcturner** [comment]
Wow, thank you so much! Your words really hit me, as it felt culpable that I delayed.

Great :smile:

**Comment by fcturner** [comment]
Implemented this as follows.

**Copy** doesn't show the password or username (in fact, the actual value doesn't even exist in the cell anymore), but pushes it directly to the clipboard:

![image](https://cloud.githubusercontent.com/assets/7526559/13076347/00a02e72-d4b2-11e5-8da2-9f113fcd3487.png)

**Share** will be working on v18 (April/May).

**Comment by fcturner** [comment]
Implemented and released: [v17](https://github.com/fcturner/passwords/releases/tag/17).
