### ISSUE TITLE
Problem with oC asset pipeline

### ISSUE THREAD

**Issue by chrsch** [fcturner/passwords#120]
If the ownCloud asset pipeline is enabled, passwords stops with a js syntax error.

Reproduce:
1) Get ownCloud 8.2.2 release
2) Enable asset pipeline in the config.php: 'asset-pipeline.enabled' => true,
3) Install passwords from github (commit c1ea58bce7c3ddbcb25b4570049e041e82743dfb) 
4) In your fresh ownCloud instance go to the passwords app and watch the js console

**Comment by fcturner** [comment]
Can you post the JS error? I can't debug with pipelines I'm afraid...

**Comment by fcturner** [comment]
@chrsch Can you please check if this error is still existing in v17?

**Comment by fcturner** [comment]
@chrsch Can you please check if this error is still existing in the new master (v18)?

**Comment by chrsch** [comment]
I will put it on my todo list and report back.

**Comment by fcturner** [comment]
:+1:

**Comment by fcturner** [comment]
Any news? Please download the latest master ([:package:zip](../archive/master.zip) or [:package:tarball](../archive/master.tar.gz)).

**Comment by fcturner** [comment]
And please reopen issue if this still exists.
