### ISSUE TITLE
JSON-characters in values throws error when decrypting

### ISSUE THREAD

**Issue by IzK666** [fcturner/passwords#121]
Hi!
I'm trying your new release v17 and after the upgrade, the website throws me several errors. This is a test server and not my real passwords :wink: I think it has to do with escape characters... again
Here are the first 3 errors thrown:

`SyntaxError: JSON.parse: Invalid escape char: "c6\ (row 1):`
`{"website" : "ABC002XH83iZvdWyO2F", "pass" : "c6\$4pjrij", "loginname" : "YRsYNE", "address" : "", "strength" : "8", "length" : "10", "lower" : "1", "upper" : "0", "number" : "1", "special" : "1", "category" : "0", "datechanged" : "2015-12-04", "notes" : "", "deleted" : "0", "id" : "14523", "user_id" : "izk"}`

`SyntaxError: JSON.parse: Invalid escape char: "kc6.jX (row 5):`
`{"website" : "ABC006XADEmhIIyhWi", "pass" : "kc6.jXWe\4]f"53U3ZZ2p2Wh&amp;", "loginname" : "kLh0iwjeDrzdqzjf6mtjX6Nd28shF", "address" : "", "strength" : "44", "length" : "25", "lower" : "1", "upper" : "1", "number" : "1", "special" : "1", "category" : "0", "datechanged" : "2015-11-26", "notes" : "", "deleted" : "0", "id" : "14527", "user_id" : "izk"}`

`SyntaxError: JSON.parse: Invalid escape char: "1g414g (row 10):`
`{"website" : "ABC011XldgNA23mgP", "pass" : "1g414g![4dk]e$q,gda-.XiU5\2\1", "loginname" : "fRuED2kvUO93SS3QfzL8tmBA3Xluw", "address" : "", "strength" : "79", "length" : "29", "lower" : "1", "upper" : "1", "number" : "1", "special" : "1", "category" : "0", "datechanged" : "2015-11-26", "notes" : "", "deleted" : "0", "id" : "14532", "user_id" : "izk"}`

**Comment by IzK666** [comment]
These are the first 11 passwords (the website begins with ABC+number):
> ABC001: 5689ifcm27Wddj\[
ABC002: c6\$4pjrij
ABC003: UaWlef
ABC004: i44qVYj%q2ZpW$gV8Yrt4b
ABC005: Xt33ohinna-sma3
ABC006: kc6.jXWe\4]f\"53U3ZZ2p2Wh&
ABC007: khg2$kn%8Z51s6Vgfg6?bV
ABC008: 1pWpi!%tYj%mW]dk?on
ABC009: eU-dg8l5[!4llu
ABC010: gqt7Vk7em
ABC011: 1g414g![4dk]e$q,gda-.XiU5\2\1

I hope it helps to solve the error.

**Comment by fcturner** [comment]
Will do, thanks!!

**Comment by fcturner** [comment]
Updated the master, would you like to check it?

**Comment by fcturner** [comment]
Can you check this too, @IzK666?

**Comment by IzK666** [comment]
Now it's different.
I deleted those 11 passwords yesterday, after notify you about the error (to have less errors), leaving  12 passwords, which throwed 3 errors.
Now, I tried to import those passwords, but it throws errors on all the imported passwords and aren't shown and the appearance is horrible:
![passwords](https://cloud.githubusercontent.com/assets/2158443/13231459/4608acbc-d9aa-11e5-9349-767221bcf8ce.jpg)
Note: Nom d'usuari = username. Contrasenya = Password
The good part is that the edit button shows the password correctly.

Luckily, I have another test server with the previous v17 (not the current version) and tried to import the passwords: It fails.
It alerts me about this error:
`SyntaxError: JSON.parse: Invalid escape char: "5689if (row 0):`
`{"website" : "ABC001Xqf3zEo34", "pass" : "5689ifcm27Wddj\[", , "deleted" : "0", "id" : "22", "user_id" : "izk"}`
and stays on the decrypting animation. Nothing else happens

**Comment by fcturner** [comment]
Huh? Now that's all wrong! Bummer...
I checked all your passwords that threw errors, they worked!

In your last error, there aren't any properties defined (login name, strength, length, ...), so it seems the update process must still take place. How is this possible? Is your login name filled in on your database? It checks for existing login names in the 'loginname' column and then performs the update.

**Comment by IzK666** [comment]
I have made an script to decrypt the BLOB values from database.
The import function isn't working properly: The properties field is an encrypted empty! Has no data. It can only retrieve the website and the password (the password field is correct).

**Comment by fcturner** [comment]
Fixed in master. HTML weren't escaped.All should look fine now.
