### ISSUE TITLE
Bugs found in version 17

### ISSUE THREAD

**Issue by IzK666** [fcturner/passwords#125]
1- Import function doesn't work. The popup that shows the passwords appears too low (half of the popup is invisible!). Even if I resize the window or anything, the popup keeps too low!

2- I have problems adding a password with a note that contains a tab like this (between "2." and "tab")
"<i>Line 2.	Tab inserted.</i>"
Throws an error and isn't showed.

3- The wheel for edit and copy in the username field appears on the left side. Was that your intention?

4- Thanks for the translation in catalan :smiley:

**Comment by fcturner** [comment]
1. I forced it to be 20 px... Strange. 

2. Never tested tabs, will look into it. 

3. Yes: when a username or password is too long, the right side will be stripped. So, when values are hidden, the wheel appears on the right. When values are not hidden, the wheel appears on the left. 

4. You're welcome!

**Comment by IzK666** [comment]
Almost solved first point: import function.
It calls an undefined variable on line 2283: browserHeight.
This variable is defined on line 2648-2653. I have copied this definition into line 2279 and works fine!

**Comment by fcturner** [comment]
Fixed (1) in https://github.com/fcturner/passwords/commit/cb5e73d039547dd2355df72c470407f14f00d62b.

Issued (2) as #127
