### ISSUE TITLE
Cant import data from Keepass

### ISSUE THREAD

**Issue by Tealk144** [fcturner/passwords#126]
Hi, if i clock on the import button and select the keepass .csv file, i get only this window.
Where i can submit?

![bild 1](https://cloud.githubusercontent.com/assets/12276250/13313468/7d1ac320-db9e-11e5-8162-b6955ed146f6.jpg)

**Comment by fcturner** [comment]
You can't, unfortunately :(

The pop up is too low and the button is off the screen. I will fix this asap.

**Comment by fcturner** [comment]
Fixed in master: https://github.com/fcturner/passwords/commit/cb5e73d039547dd2355df72c470407f14f00d62b

I will close this issue with the release of 17.1 next week.

**Comment by Tealk144** [comment]
Ok thank you, have fixt it fast with your code snippes :D

**Comment by tgutwin** [comment]
The five line patch also worked well for me on 17.
FIXED!
thanks

**Comment by csaq7114** [comment]
used the same snipped, without success. Im using chromium 48, with owncloud 8.2

**Comment by fcturner** [comment]
Checked, fixed now (in master).
