### ISSUE TITLE
Creating notes containing tabs doesn't work properly

### ISSUE THREAD

**Issue by fcturner** [fcturner/passwords#127]
>@IzK666 
I have problems adding a password with a note that contains a tab like this (between "2." and "tab")
"Line 2. Tab inserted."
Throws an error and isn't showed.

**Comment by fcturner** [comment]
Please check if this solves it: https://github.com/fcturner/passwords/commit/d3ea41fe4cfb5f593418c1664387b45edafabab2 (it does with me)

**Comment by IzK666** [comment]
Works perfect!

Thank you!
:smile:
