### ISSUE TITLE
Loop after Upgrade to version 17

### ISSUE THREAD

**Issue by weipah** [fcturner/passwords#129]
I pulled the new version via Git and now when I open the app in OC I get the following messages in a loop.

![image](https://cloud.githubusercontent.com/assets/1555658/13375748/307fecaa-dda8-11e5-9acc-e1483f504887.png)

![image](https://cloud.githubusercontent.com/assets/1555658/13375751/3f83ba06-dda8-11e5-824b-8e844c4356ae.png)

After reloading I get the first one again.

I checked the database and there is no table '**oc_passwords_categories**', just '**oc_passwords**'.

Any idea what could possibly be wrong here?

**Comment by fcturner** [comment]
This is very odd. It means ownCloud didn't do a database upgrade after you installed and activated the app. This is not something an app can do for you and looks like an ownCloud bug. 
The new version of my app works very well with other users, so I can't explain this behaviour. 

Never got an alert message from ownCloud itself when you activated the app?
You can create the database table for categories yourself. The database scheme is in appinfo/database.xml. 
Are you using MySQL? Then I can post the query here (I'm on mobile now, need to look it up first). 

Please let me know! I'm sorry that you ran into this.

**Comment by fuerst** [comment]
Same for me. Adding the `passwords_categories` table did not help because table `passwords` is missing the field _properties_ too. Since I had a copy of my passwords I decided to reinstall the app which removes all of your password records. Reinstalling means: disabling the app, dropping table `oc_passwords`, deleting passwords records from table `oc_appconfig` and enabling the app again.

Maybe the app is missing an _appinfo/update.php_ file which takes care of updating the database structure. See _apps/contacts/appinfo/update.php_ for an example.

**Comment by weipah** [comment]
@fcturner I updated my of version first with **php occ upgrade** command. 
After this 3rd party appa were disabled in backend. 

I reactivated the app without error. Then I pulled new version from passwords app. 

I will try to update the dB manually with the according scripts and see how it turns out.

**Comment by fcturner** [comment]
Never heard of an update.php. It wasn't needed prior to ownCloud 8.2. 

[sarcasm] Nice of the ownCloud developers that they change everything every point release and write everything down in a manual, really works well for app developers. [/sarcasm]

I will look into this. Thanks.

**Comment by weipah** [comment]
@fcturner yes, to be honest almost every OC release f*cks up something with my installation, although I think I have pretty much a standard setup, nothing special.

**Comment by fcturner** [comment]
`apps/contacts/appinfo/update.php` doesn't contain any `CREATE TABLE` statements, only `UPDATE`. Creating new tables should really happen when refreshing the page after an update by ownCloud, not this app.

My `database.xml` starts with:
```xml
<database>
	<name>*dbname*</name>
	<create>true</create>
	<overwrite>false</overwrite>
	<charset>utf8</charset>
```
So it should be created. I don't what will happen when I set `<overwrite>` to `TRUE` though...

**Comment by fcturner** [comment]
Please download master to check if this has been solved.

**Comment by fcturner** [comment]
It will trigger an update, since it's 17.1.

**Comment by weipah** [comment]
@fcturner pulled the new version and did the upgrade process.
Now it works! Thanks a lot for your effort!
