### ISSUE TITLE
Possibility to assign labels to passwords, with entry in navigation bar (left)

### ISSUE THREAD

**Issue by fcturner** [fcturner/passwords#13]
- [x] A way to add labels to passwords (need hashing??)
- [x] Add created labels to navigation bar

**Comment by fcturner** [comment]
Idea by Nemofly: http://apps.owncloud.com/content/show.php?content=170480#c476759

**Comment by Nemofly** [comment]
Maybee something like Keepass. This Software has an Tree you ca do by yourself.
That will be great ;)
Thanks a lot!

**Comment by Tramour** [comment]
Seconded.

**Comment by fcturner** [comment]
Great idea, but it [looks a bit cluttered](http://keepass.info/screenshots/keepass_2x/main_big.png) to me. Besides, it won't fit in the navigation pane due to ownCloud 'restrictions' (or: advice for app coding).

I was more thinking about a collapsible list.

**Comment by fcturner** [comment]
This is also an idea by @glegerand in #20

**Comment by fcturner** [comment]
Will be on v17.

**Comment by Tramour** [comment]
:thumbsup:

**Comment by fcturner** [comment]
Almost done with v17! I'm sorry that it takes some more time.

**Comment by fcturner** [comment]
Finally! Took some months, but now implemented and released: [v17](https://github.com/fcturner/passwords/releases/tag/17).

**Comment by Tramour** [comment]
Thank you for the great effort you put into this! Works like a charm ;-)

**Comment by fcturner** [comment]
Thanks! :+1:
