### ISSUE TITLE
Collate query not supported on sqlite

### ISSUE THREAD

**Issue by egde** [fcturner/passwords#130]
Hi,

I've upraded this app to version 17 on a Owncloud 8.1.5.2. When starting ownloud, the databases were updated. I see that I have a categories table now. However when I use the app in Owncloud the following errors occur:

Error: Could not load passwords.
<img width="570" alt="screen shot 2016-02-28 at 18 59 08" src="https://cloud.githubusercontent.com/assets/4752846/13380903/1ae1230e-de4e-11e5-84f5-79d62a3231c5.png">
Error: Could not load categories.
<img width="413" alt="screen shot 2016-02-28 at 18 59 48" src="https://cloud.githubusercontent.com/assets/4752846/13380908/2f5a1336-de4e-11e5-9ac9-5147fd6726de.png">

Afterwards it shows the message that it is trying to decrypt the message and ends there.
<img width="487" alt="screen shot 2016-02-28 at 18 59 57" src="https://cloud.githubusercontent.com/assets/4752846/13380909/32b32d74-de4e-11e5-85bb-5f7df7c71459.png">

**Comment by egde** [comment]
Ok, got it fixed.

The SQLs in the passwordmapper.php and categorymapper.php cannot be run on an sqlite3 database.

Remove the Collate part in the SQL.

**Comment by fcturner** [comment]
Thanks for figuring this out! I can fix this, will be in 17.1.

**Comment by fcturner** [comment]
Type of used db is defined in config.php, so I can test for that.

**Comment by egde** [comment]
Exactly - I saw it now, too.
Sweet:)

**Comment by fcturner** [comment]
Fixed!
Here for passwords: https://github.com/fcturner/passwords/commit/78ac1806e086747e297aa0a6545949d9aa705a2c
Here for categories: https://github.com/fcturner/passwords/commit/66a66768638a191765fa0718e5db55c707d4777b

Master is up to date, so [downloading it](https://github.com/fcturner/passwords/archive/master.zip) will solve this.

**Comment by fcturner** [comment]
(fixed for PostgreSQL too, by the way)

**Comment by egde** [comment]
Thanks! I will give it a try tonight/tomorrow.

**Comment by egde** [comment]
Played in your fix. It works!

Thanks for your effort!

**Comment by fcturner** [comment]
:+1:
