### ISSUE TITLE
Why using Flash?

### ISSUE THREAD

**Issue by Salzi** [fcturner/passwords#131]
Is there a reason why you using flash to copy passwords to the clipboard? Flash is not known to be very safe.

**Comment by fcturner** [comment]
If you know another way to copy values directly to clipboard for every browser, please let me know. 

It must support IE, Firefox, Chrome and Safari. Especially the last one makes it hard; and it is pre installed on every Mac so I want to support that.

**Comment by fcturner** [comment]
And please bring arguments against ZeroClipboard specifically.

**Comment by Salzi** [comment]
Well this was just a question I'm not a web developer. I was just wondering why you are using flash. I do not need flash on my system any more because for me there is no good reason to still use it. Every few days someone find an other a new vulnerability in flash... And most annoying ads are in flash.

However a quick google search show me the reason: Safari doesn't support a plain js solution. But it looks like ZeroClipboard itself is working on a solution: https://github.com/zeroclipboard/ZeroClipboard/issues/171
This could be an other solution: https://clipboardjs.com/ (it has a safari fall back)

**Comment by Salzi** [comment]
Just saw that http://www.emoji-cheat-sheet.com/ also using ZeroClipboard but there the copying works without flash. Maybe you're just using an older version?

**Comment by fcturner** [comment]
I use their latest version, pulled just before the release of v17. 

On iPhone and Chromium (both no Flash) it still doesn't work on that website, so there's no big advantage.

I will look into other alternatives, however, as I don't like Flash. As a matter of fact, I don't like Adobe at all.

**Comment by haeckle** [comment]
What about this: http://stackoverflow.com/a/30810322 
Don't know if it works with iPhone or other mobile browsers, but at least the major desktop browsers seems to support it.

**Comment by marius-wieschollek** [comment]
I use firefox with and this copy thing doesn't work on any of my pc's. Not with windows 8/10 nor with linux. Maybe the HTML5 copy solution will do better: http://stackoverflow.com/a/32340088

**Comment by fcturner** [comment]
Firefox works here. Please tell me what doesn't work. Do you get the prompt window instead?

Like I said 23 days ago:
>It must support IE, Firefox, Chrome and Safari. Especially the last one makes it hard; and it is pre installed on every Mac so I want to support that.

**Comment by fcturner** [comment]
Guess I'll support both; Flash still for Safari. 

I will take a look.

**Comment by fcturner** [comment]
Flash will be killed in v19 in favour of Clipboard.js. Stay tuned.
