### ISSUE TITLE
Cannot enable app: Library mcrypt is not available

### ISSUE THREAD

**Issue by reuterbal** [fcturner/passwords#132]
Hi,

thanks for providing such a useful app. Today I wanted to try out the passwords app on my OwnCloud 8.2.2 instance on Ubuntu 14.04.4 but ran into troubles when trying to activate it.

Steps to reproduce:

- Install passwords 
```
cd /path/to/owncloud/apps
git clone https://github.com/fcturner/passwords.git
cd passwords
git checkout tags/17
```

- Try to activate passwords via OwnCloud Apps
The app shows up with correct version number (17) but "Enable" is greyed out and the following error message is provided:

> This app cannot be installed because the following dependencies are not fulfilled:
> 
>   - The library mcrypt is not available.

However, mcrypt is available:

```
# dpkg -l *mcrypt*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                Version                        Architecture                   Description
+++-===================================================-==============================-==============================-============================================================================================================
ii  libmcrypt-dev                                       2.5.8-3.1ubuntu1               amd64                          De-/Encryption Library development files
ii  libmcrypt4                                          2.5.8-3.1ubuntu1               amd64                          De-/Encryption Library
ii  mcrypt                                              2.6.8-1.3                      amd64                          Replacement for old unix crypt(1)
ii  php5-mcrypt                                         5.4.6-0ubuntu5                 amd64                          MCrypt module for php5
```

Additionally, phpinfo() shows the mcrypt extension and, e.g., phpMyAdmin is able to use it.

Any ideas?
Thanks!

**Comment by fcturner** [comment]
How strange! I don't know how ownCloud checks for this, seems an ownCloud bug. 

You can try how it works if you bypass the test. Edit passwords/appinfo/info.xml and remove the line:
<lib>mcrypt</lib>

Please let me know if the app still works!

**Comment by reuterbal** [comment]
Thanks for the fast response!
Apparently OwnCloud's check for mcrypt is correct. Installing php5-mcrypt in Ubuntu does not actually enable the mod - a simple `php5enmod mcrypt` was missing.
Bypassing the test, it failed to create any new passwords, complaining about undefined function mcrypt_create_iv() in the logs.
It's not a bug on your side!

I have some trouble importing passwords from Password Exporter or KeePass CSV-files. It fails after few passwords, with a message telling me that the session expired, and the page reloads. However, nothing is logged. A quick glance at the code suggests that you did not yet implement any error handling on that part but that the provided message and reload happens whenever there is any error during import. I'll guess I'll try the plugin with some passwords provided via the UI for now.

**Comment by fcturner** [comment]
I'll fix the error handling. Thanks for the feedback!
