### ISSUE TITLE
Owncloud 9.0 Support

### ISSUE THREAD

**Issue by Salzi** [fcturner/passwords#135]
Current version seems not to work with owncloud 9.0. After upgrade an error window with the message: 

> "Error: Could not load passwords." 

appears.
In the Log there is an Error:

>  Class 'OC_Config' not found at /var/www/owncloud/apps/passwords/service/passwordservice.php#25

**Comment by timscha** [comment]
Can confirm, the app does not work on OC9.
I got the following if I want to import an csv (tried with your 17.1 fix already):

```
Error	PHP	Error: Class 'OC_Config' not found at /var/www/owncloud/htdocs/apps/passwords/service/passwordservice.php#25
Error	PHP	Error: Class 'OC_Config' not found at /var/www/owncloud/htdocs/apps/passwords/service/passwordservice.php#76
```

**Comment by Salzi** [comment]
I was able to fix it by replacing the line
`$serverKey = \OC_Config::getValue('passwordsalt', '');`
in the file service/passwordservice.php
by
`$config = \OC::$server->getConfig();`
`$serverKey = $config->getSystemValue('passwordsalt', '');`
I'm not a web developer so I don't know if this is the correct way to do it. If so and if that helps I could create a PR.

**Comment by timscha** [comment]
@Salzi Can confirm, your fix worked for me. :) :+1:

**Comment by IzK666** [comment]
In a single command:
$serverKey = \OC::$server->getConfig()->getSystemValue('passwordsalt', '');

Confirmed that works on OC8.1 and 8.2.1 too

**Comment by timscha** [comment]
The fix have to be on more lines. In my version on line 76 and 103 (without I cannot delete entries).

**Comment by fcturner** [comment]
Great work guys :+1:
