### ISSUE TITLE
OC9 after enabling app and opening white screen

### ISSUE THREAD

**Issue by apg1980** [fcturner/passwords#137]
After enabling passwords app in oc9 white screen appears.
This is not happening in oc 8.2.3.
oc log:
{"reqId":"QFZ7Mhzp3uPWtAf3ZXWC","remoteAddr":"10.10.20.10","app":"PHP","message":"Class 'OC_Config' not found at \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/apps\/passwords\/templates\/main.php#16","level":3,"time":"2016-03-10T07:02:06+00:00"}

**Comment by fcturner** [comment]
Thanks for letting this know!

This is already fixed here: #135. I will release 17.1 today, which supports ownCloud 9.0.
