### ISSUE TITLE
Full API

### ISSUE THREAD

**Issue by thefirstofthe300** [fcturner/passwords#140]
I am starting to work on a Chrome extension for my own needs.  First time building an extension and first time working with an Owncloud app.  Where can I find the API for this app?  Is this something that ownCloud core does?  Or do you have an API exposed in your app?

I am looking through the FF extension but it would be nice to have some API documentation so I know what the heck is going on.

**Comment by fcturner** [comment]
First of all, thank you for creating this!!
I will write a documentation. 

For now: my app supports extensions by using a RESTful API, and using it is rather simple.
@eglia, also for you to know.
* Address for passwords: `https://www.yourdomain.co.uk/index.php/apps/passwords/api/0.1/passwords`
* Address for categories: `https://www.yourdomain.co.uk/index.php/apps/passwords/api/0.1/categories`

You can test this on a server with:
```
curl -u yourusername:yourpassword https://www.yourdomain.co.uk/index.php/apps/passwords/api/0.1/passwords
```

It returns a decrypted, valid JSON string, like:
```json
[
	{
		"id":60,
		"user_id":"ownclouduser1",
		"loginname":"",
		"website":"google.com",
		"address":"",
		"pass":"testpassword1",
		"properties":
			"\"loginname\" : \"testusername1\",
			 \"address\" : \"\",
			 \"strength\" : \"4\",
			 \"length\" : \"13\",
			 \"lower\" : \"1\",
			 \"upper\" : \"0\",
			 \"number\" : \"0\",
			 \"special\" : \"0\",
			 \"category\" : \"0\",
			 \"datechanged\" : \"2014-11-15\",
			 \"notes\" : \"\"
			",
		 "notes":false,
		"creation_date":"0000-00-00",
		"deleted":"0"
	},
	{
		"id":61,
		"user_id":"ownclouduser2",
		"loginname":"",
		"website":"google.com",
		"address":"",
		"pass":"testpassword2",
		"properties":
			"\"loginname\" : \"testusername2\",
			 \"address\" : \"\",
			 \"strength\" : \"4\",
			 \"length\" : \"13\",
			 \"lower\" : \"1\",
			 \"upper\" : \"0\",
			 \"number\" : \"0\",
			 \"special\" : \"0\",
			 \"category\" : \"0\",
			 \"datechanged\" : \"2014-11-16\",
			 \"notes\" : \"\"
			",
		 "notes":false,
		"creation_date":"0000-00-00",
		"deleted":"0"
	}
]
```
You can check on these values.

**Comment by fcturner** [comment]
**NOTE**: from the next version on (already implemented in master), only `GET` statements are allowed, so the API only has read access.

**Comment by thefirstofthe300** [comment]
Don't thank me just yet. I still haven't gotten past the research stage. :)

Thanks for letting me know about the api!

**Comment by eglia** [comment]
What's the reasoning behind making the API read only? It prevents implementation of certain features, e.g. https://github.com/eglia/ff-oc-passwords/issues/6

**Comment by fcturner** [comment]
Answered there.

**Comment by thefirstofthe300** [comment]
So for those of you who wish to help me with my extension (and any help is appreciated!), you can find my repo [here](https://github.com/thefirstofthe300/ownCloud-Passwords).

**Comment by fcturner** [comment]
Anyone getting here from another source: the documentation is in my wiki here:
<https://github.com/fcturner/passwords/wiki>
