### ISSUE TITLE
Token expired

### ISSUE THREAD

**Issue by eglia** [fcturner/passwords#141]
I'm running into some issues with the firefox plugin I could use your help with.
See [https://github.com/eglia/ff-oc-passwords/issues/4]. Apparently, each time the plugin accesses the API, the login token gets regenerated and the currently open ownCloud page has to be reloaded. This can easiest be seen in the News app: Open the news app, refresh the Firefox plugin, try to do anything in the news app => "Token expired, please reload".

I know hardly anything about ownCloud, so I don't know if that is expected behaviour or if anything can be done about this.

As requested in #140 an API documentation would be nice :blush: Currently, I'm calling index.php/apps/passwords/api/0.1/passwords and send the login information as basic httpauth headers. This returns a big JSON object containing all the data. Is this the intended usage?

**Comment by eglia** [comment]
Ok I got it working. Apparently I was sending the session cookies as well as the auth headers with each request.

**Comment by fcturner** [comment]
:+1:
