### ISSUE TITLE
ZeroClipboard not loaded

### ISSUE THREAD

**Issue by eglia** [fcturner/passwords#142]
ZeroClipboard.swf is not loaded in my ownCloud (9.0.0), neither under Linux (Firefox) nor under Windows (Firefox/IE). The firefox console shows that the request for the file gets a response 302:

GET /owncloud/apps/passwords/js/ZeroClipboard.swf?noCache=1458066781665 HTTP/1.1
Host: [...]
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
DNT: 1
Cookie: [...]
Connection: keep-alive

HTTP/1.1 302 Found
Date: Tue, 15 Mar 2016 18:33:00 GMT
Server: Apache/2.4.7 (Ubuntu)
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
X-Powered-By: PHP/5.5.9-1ubuntu4.14
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
content-security-policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
Location: https://[...]/owncloud/index.php/apps/files/
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Frame-Options: SAMEORIGIN
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Content-Length: 0
Keep-Alive: timeout=5, max=91
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8

Passwords app is latest version from git.

**Comment by fcturner** [comment]
Doesn't 302 mean that the file has been found but was moved? Are you perhaps forgetting a www. in your URL? 

It actually works on my OC9...

**Comment by eglia** [comment]
I think it does... But there is now www in my host, the url is correct. It seems as though some server configuration prevents access to .swf files...

Quick testing showed that removing the .htaccess in the owncloud root solves the problem.
I also noticed that the loading also does not work if asset pipelining is enabled.

**Comment by eglia** [comment]
I did some further testing. If I change this line in .htaccess:
RewriteCond %{REQUEST_FILENAME} !\.(css|js|svg|gif|png|html|ttf|woff|ico)$
to
RewriteCond %{REQUEST_FILENAME} !\.(css|js|svg|gif|png|html|ttf|woff|ico|swf)$
it works (without asset pipelining).
In the core git there seem to have been some changes to the .htaccess which could solve this with the new release...

**Comment by fcturner** [comment]
Alright, thanks for testing. 

So I should just wait for ownCloud 9.0.1?

**Comment by eglia** [comment]
I don't think there's anything else you can do :)

Except maybe for the asset pipelining, but I know nothing about how that works.

**Comment by fcturner** [comment]
Alright then. Thanks again! :+1:

**Comment by fcturner** [comment]
#157
