### ISSUE TITLE
App throwing bad JSON in properties

### ISSUE THREAD

**Issue by thefirstofthe300** [fcturner/passwords#146]
I am working with eglia to get the Firefox plugin working for me and it appears that the app is throwing some bad JSON.  I sent you a link to the output JSON minus all the password lines.  It should be going to the GitHub email.  As far as I can tell, the actual JSON output of the app is valid; the problem lies in the JSON in the properties lines somewhere.  Also, I imported all of these passwords from a CSV file if that will make a difference.

EDIT: I narrowed the problem down to the ONE password that has a note.  If I import that one password, the crap hits the fan.

**Comment by fcturner** [comment]
Does the note has any JSON or HTML characters, like quotation marks, brackets and so forth?
If it has, are they escaped by another character like backslash?
I don't see an email...

**Comment by fcturner** [comment]
Any news?

**Comment by fcturner** [comment]
Please download the latest master ([:package:zip](../archive/master.zip) or [:package:tarball](../archive/master.tar.gz)) to check if this still exists.

**Comment by fcturner** [comment]
And please reopen issue if this still exists.
