### ISSUE TITLE
API PATCH returns 405 Method not allowed

### ISSUE THREAD

**Issue by eglia** [fcturner/passwords#148]
When I try to modify an element using PATCH I get an error 405: Method not allowed. If I send the exact same request as PUT, it works.

**Comment by fcturner** [comment]
Now that's strange, giving that ([passwordapicontroller.php](https://github.com/fcturner/passwords/blob/master/controller/passwordapicontroller.php#L17-L27)):
```php
public function __construct($AppName, IRequest $request, PasswordService $service, $UserId) {
	// allow getting passwords and editing/saving them
	parent::__construct(
		$AppName,
		$request,
		'GET, POST, DELETE, PUT, PATCH',
		'Authorization, Content-Type, Accept',
		86400);
	$this->service = $service;
	$this->userId = $UserId;
}
```
It should work. I don't know?!

**Comment by eglia** [comment]
Well does it work for you?
`curl -i -X PATCH -u [user] https://[owncloud]/index.php/apps/passwords/api/0.1/passwords`
returns `HTTP/1.1 405 Method Not Allowed` for me. Maybe it's a server configuration issue...

**Comment by fcturner** [comment]
Nope: `HTTP/1.1 405 Method Not Allowed`

But if I run
`curl -i -X OPTIONS -u [user] https://[owncloud]/index.php/apps/passwords/api/0.1/passwords/[id]`
the header returns
`Access-Control-Allow-Methods: GET, POST, DELETE, PUT, PATCH`

I really don't get it. You could stick to `PUT`, I guess...

**Comment by fcturner** [comment]
Looks like the ownCloud public API doesn't support it:
https://doc.owncloud.org/api/classes/OCP.Http.Client.IClient.html

**Comment by fcturner** [comment]
I close this for now, looks like lack of support by ownCloud. As PUT does work, PATCH isn't really needed.  I'll update the wiki page.
