### ISSUE TITLE
Get version over API

### ISSUE THREAD

**Issue by eglia** [fcturner/passwords#154]
In order to prevent interaction with incompatible versions, it would be nice if there was a possibility to get the version of the passwords app over the API.

**Comment by fcturner** [comment]
Will #155 work? What do you think?

**Comment by fcturner** [comment]
I don't know how to return the version number. I would like to use the password generator over API too, since that would be needed for an iOS or Android app.

**Comment by eglia** [comment]
Maybe I'm missing something but I don't see that change having any effect. If the version is below 17, then this check is not there yet, and if the check is there then the version is above 17.

**Comment by fcturner** [comment]
Yes, but that's also true for using POST commands; they weren't available in v16.2 and lower, were they?

So the extension must check for the app version. If I create an API possibility for returning a version number, then that function itself would prove availability of v17 or later. So there's no point in changing something here for this purpose.

**Comment by eglia** [comment]
I can check fairly easily if the app is older than v17 by looking for the properties tag. Then I'll just abort. But more than that would be rather complex.
If you include a version API in the next release, I can check for that. If it doesn't exist, it means the version is between v17 and v17.2. So I can fetch and fill passwords without problem, but I should not try to add new ones.
It can also prove useful in the future, if some feature is added that requires a certain version of the app I can check for that and notify the user if the app is outdated.
