### ISSUE TITLE
Copy button not work on OC9.0.0

### ISSUE THREAD

**Issue by dva-re** [fcturner/passwords#157]
Since i was update OC from 8.1 to 9.0
.htaccess contains next lines

`# Rewrite rules for front_controller_active`
`  ...`
`  RewriteCond %{REQUEST_FILENAME} !\.(css|js|svg|gif|png|html|ttf|woff|ico)$`
`  ...`
`  RewriteRule .* index.php [PT,E=PATH_INFO:$1]
`

So, the url _/apps/passwords/js/ZeroClipboard.swf_ rewrited to index.php and swf does not load.

Workaround: change line to  
`  RewriteCond %{REQUEST_FILENAME} !\.(css|js|svg|gif|png|html|ttf|woff|ico|swf)$`

**Comment by fcturner** [comment]
This is an ownCloud bug, they have already fixed and will be in their release.

**Comment by fcturner** [comment]
#142
