### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by juhulian** [fcturner/passwords#158]
Hey,
i tried to install the passwords app, but after activating the app i just got a blank page (also for the admin page).
I found 2 entries in the logs:
Error PHP Undefined constant 'OCA\Passwords' at /var/www/owncloud/apps/passwords/templates/admin.settings.php#3
and
Error PHP Undefined constant 'OCA\Passwords\Controller' at /var/www/owncloud/apps/passwords/controller/pagecontroller.php#2
Any ideas?

**Comment by fcturner** [comment]
Fixed! Removes some slashes. Please download master again.
