### ISSUE TITLE
Passwords are all shown and directly usable by others when leaving desk

### ISSUE THREAD

**Issue by oparoz** [fcturner/passwords#16]
In the view, passwords should be replaced with ****, like on keypass and be decrypted on demand, by clicking a little view icon like on mobile. They should only be available in memory for a short while.
It could be even better if the oC password could be asked when revealing passwords and there would also be a time out on that.

**Comment by fcturner** [comment]
Good point. But opening the app is your own responsibility, and passwords are only visible when you are in the Passwords app. Handlebars handle the loading, so it only gets loading after HTML page load. JS only with PHP decryption. So why ask for the ownCloud password when clicking on a field with ****? You should just open the app, click on a password to copy it manually, click on the website and close the app. Isn't that 'a short while' enough?
I could implement your idea, but I assumed no one is accessing the app on a projector in a board room meeting... I actually think your idea is rather redundant in terms of security, and yields less pragmatical use for no good reason.

I will keep this issue open, looking forward to your response :)

**Comment by oparoz** [comment]
Lots of people leave their desk unattended and it's easy for someone to switch from the files app to the password app and have access to all the passwords, unless you're asking for the password when opening the app.
Also, it's easy to take a picture and have access to all the passwords being displayed on the page.

There must be other reasons since all the password managers I know are either doing it by default or offer the option.

What does @LukasReschke think?

**Comment by fcturner** [comment]
Great explanation. Really. I didn't think of both those things. I will think of something to implement this. Stay tuned!

**Comment by oparoz** [comment]
:) :dancers:

**Comment by fcturner** [comment]
One thing: asking for the ownCloud password feels really clumsy, especially when you don't use this at work or other public places. But then again, how many people don't? Maybe an option on the Personal page?

**Comment by oparoz** [comment]
I'm all for optional settings :)
And maybe that option could ask the user for how long the password should be cached for.

**Comment by fcturner** [comment]
Right.
I don't know how to keep track of a time based interval, like after entering the ownCloud password. The only way I know (and of which I am able to do), is asking for the ownCloud password every single time a **** is clicked. Not a bad thing either. 

Just an option on the personal settings to enable or disable this should be fine, I guess.

**Comment by oparoz** [comment]
You should be able to start a loop with setTimeout and call the locking method when it expires.
Makes sense?

**Comment by oparoz** [comment]
My initial idea was to send the value back to PHP so that it can't be manipulated...
I haven't tested this, but I imagine that using the debugging console, a user could reset the timer to a very large value.

**Comment by fcturner** [comment]
Now here comes the challenge :smile: 
It is true that this can be edited, since Javascript is client-side. But PHP would require more database-code. This enhancement will be something to learn from!

**Comment by oparoz** [comment]
Yes, you would probably need to store the value in the DB, in case the stream gets disconnected and then use `createEventSource()` and `$eventSource->send()` on the PHP side and `OC.EventSource` on the JS side.

**Comment by fcturner** [comment]
@oparoz 
Passwords now hidden by https://github.com/fcturner/passwords/commit/4f7d7a02a195f36c928a33b0c5390f063e8c6230 (CSS-only, working on PHP/JS).

Implemented in master and in [8.0.4](https://github.com/fcturner/passwords/releases/tag/8.0.4).

**Comment by oparoz** [comment]
Nice first step, thanks :)

**Comment by fcturner** [comment]
Fixed with the 8.0.6 release (https://github.com/fcturner/passwords/commit/aa76297a04e9f3d18bf5ff189aa8bbc531e7a174)

Settings on Personal page. Cache is a little too far from my bed... Would you like to code this yourself and create a pull request?
