### ISSUE TITLE
Apps-menu link points not to apps/passwords

### ISSUE THREAD

**Issue by juhulian** [fcturner/passwords#163]
The link in the apps menu points to the latest visit app-site (see attached picture) instead of apps/passwords.

![screenshot_2016-03-27_13-41-59](https://cloud.githubusercontent.com/assets/5305965/14065274/98c2e902-f423-11e5-9b09-041fb7f08f6b.jpg)

**Comment by fcturner** [comment]
Never heard of this bug. And I can't reproduce it. The file where this is defined, seems to work correctly. Which ownCloud version are you using? 

You issued some other bugs, so how come this has never been a problem before?

**Comment by juhulian** [comment]
Sorry for posting this issue, it looks as if it was a cache trouble, now all works create! thx for this app and the fast responses!

**Comment by fcturner** [comment]
:wink:
