### ISSUE TITLE
"Error: Could not load passwords." After upgrade

### ISSUE THREAD

**Issue by florianaudon** [fcturner/passwords#164]
Hello,

I've upgrade my owncloud from 8.0.3 to 9.0.
Everything is fine for the owncloud's core. But the passwords app doesn't work anymore.
When I load the application. There are the error "Error: Could not load passwords."

Someone can help me to resolve this error?
Thank you

**Comment by fcturner** [comment]
What does the log say? Which versions are you using? Must be 17.1 or later, since before that, Passwords doesn't work on OC9.

**Comment by florianaudon** [comment]
The log say: "PHP message: PHP Fatal error:  Class 'OC_Config' not found in /usr/share/nginx/www/owncloud/apps/passwords/service/passwordservice.php on line 25"
The version is: 16.2

**Comment by florianaudon** [comment]
It's ok.
I've git clone this repo to update to last version and I've have no errors anymore

Sorry for disturbing.

**Comment by fcturner** [comment]
No problem!! You had an older version that didn't support OC9.

I just finished the sharing function! Will release it this or next week. Stay tuned :smile:
