### ISSUE TITLE
endless cycle after deleting database tables

### ISSUE THREAD

**Issue by morriswinkler** [fcturner/passwords#166]
i deleted passwords tables and appconfig.passwords

now i am stuck between an ever cycling 

ein Update wird benötigt
Laydrop Passwörter wurde zu Version 18.0 aktualisiert, ein Update Ihrer Password-Liste ist nötig. Bitte schließe das Fenster während des Updates nicht.

Das Update ist fertig. Die Seite muss nun aktualisiert werden.
Aktualisieren

and than back to the top

**Comment by fcturner** [comment]
Thanks for testing the sharing function. 

Well, that's not right :wink:
I'll get back to that.

**Comment by fcturner** [comment]
Thanks for testing the sharing function. 

Well, that's not right :wink:
I'll get back to that.

**Comment by fcturner** [comment]
I checked the code; it only requires an update if you have some database entries where your login name is still saved as plain text in the `oc_passwords.loginname` column. That column should be empty. Can you check that? If it does contain some values, you do need an update. 

In case your previous versions was v16.2 or lower (and thus you need an update): did you click `Aktualisieren`?

**Comment by fcturner** [comment]
Wait, you deleted everything... Maybe it has something to do with Handlebars.

**Comment by fcturner** [comment]
Found the bugs and killed them.
