### ISSUE TITLE
Create different Password use Cases

### ISSUE THREAD

**Issue by benedikt-d** [fcturner/passwords#167]
I'm asking myself if it makes sense to create different required fields for different types of password. For example if I store a Password which is not for a website. Like my WIFI Password or my email login. I always need to type in a valid URL. In that case I think a url does not make any sense.

Also I'm asking myself it is possible to sync the passwords with my local password manager on my Computer. Like the OSX Keychain or LastPass. Not sure if Keychain or Lastpass even has that possibility.

**Comment by fcturner** [comment]
Thanks for participating on this project!

> I always need to type in a valid URL.

No, you don't. The URL, notes and categories are all optional. You only need to set a website/company name/whatever (`site.com or Name Inc.` in screenshot below), a login name and a password:
![image](https://cloud.githubusercontent.com/assets/7526559/14134507/13ff366c-f658-11e5-8a77-14193a2c16ad.png)
Just leave the `Full URL (optional)` field blank and you're good to go. Only need to set the bottom three. I myself have a password like this (no URL used):

| Website or company | Login name | Password |   Strength  |
|:------------------:|:----------:|:--------:|:-----------:|
|      Apple ID      |  appleuser |  ******  | Strong (56) |


-------------------


>Also I'm asking myself it is possible to sync the passwords with my local password manager on my Computer. Like the OSX Keychain or LastPass. Not sure if Keychain or Lastpass even has that possibility.

Sharing is possible between browsers (there is a [Firefox addon available](https://addons.mozilla.org/en-US/firefox/addon/firefox-owncloud-passwords) and a [Chrome extension on its way](https://github.com/thefirstofthe300/ownCloud-Passwords)), but it can become available to every other source (like OS X Keychain), if it supports the use of an API. Thru an API, practically everything is possible. I don't think LastPass is a good way to go. You should use either LastPass or ownCloud Passwords (which contains safe sharing from next week on). My app can export to LastPass and import from it too.
