### ISSUE TITLE
inactivity countdown changes arent without any effect

### ISSUE THREAD

**Issue by benginoe** [fcturner/passwords#172]
the inactivity countdwon can be changed in the personal user settings area, but changes there dont effect the app behavior

example:

i changed the time in my personal settings to 30 minutes (1800 seconds) but this doenst change the time after which i will be log outed of my account.

**Comment by fcturner** [comment]
Seeing this?

![image](https://cloud.githubusercontent.com/assets/7526559/14174230/66ce8f8c-f743-11e5-8668-82c9ddd27a13.png)

That's not a user setting; everything works fine. The setting cookie is at default set to an expiration of 1 minute, as the personal settings tell you too:

![image](https://cloud.githubusercontent.com/assets/7526559/14174277/af77fce6-f743-11e5-95d6-4e0eee75a77f.png)

This has to be changed by the admin in config.php.

Am I right?

**Comment by fcturner** [comment]
(changed default to 15 minutes for v18)

**Comment by fcturner** [comment]
Guess this can be closed. Please reopen if the issue persists.
