### ISSUE TITLE
Hiding columns "Strength" and "Last Changed" strange behaviour

### ISSUE THREAD

**Issue by roru69** [fcturner/passwords#173]
When hiding columns "Strength" and "Last Changed" the Column headers don't hide so the columnheaders  are misaligned with the actual columns.

**Comment by fcturner** [comment]
This is fixed already in #139. Will be in next version (v18, which contains sharing too) to be released this or next week.

You can [download the latest version already](https://github.com/fcturner/passwords/archive/master.zip), but might miss a bugfix or two.

**Comment by fcturner** [comment]
Thanks anyway for letting me know this!!

**Comment by roru69** [comment]
Ok. Thanks. Sorry. Wasn't paying attention i guess.. ;-)
