### ISSUE TITLE
Problem after deleting database

### ISSUE THREAD

**Issue by morriswinkler** [fcturner/passwords#177]
ok the following ocurs:

i get firts 

"ein Update wird benötigt"

than i run that and it runs over a  html table called PasswordsTableTestOld

in that table are many rows, one for every of my users

looking like 
```
<tr>
				<td></td>
				<td>user</td>
				<td></td>
				<td></td>
				<td></td>
				<td>0</td>
				<td>user</td>
				<td></td>
				<td></td>
				<td></td>
			</tr>

```

than the java script makes a server put for every user like:

```
jquery.min.js?v=4d4b2e4…:6 PUT https://owncloud.myserver.com/index.php/apps/passwords/passwords/0 

500 (Internal Server Error)send @ jquery.min.js?v=4d4b2e4…:6x.extend.ajax @ jquery.min.js?v=4d4b2e4…:6Passwords.updateActive @ script.js?v=4d4b2e4…:152updateStart @ script.js?v=4d4b2e4…:2985(anonymous function) @ script.js?v=4d4b2e4…:290x.event.dispatch @ jquery.min.js?v=4d4b2e4…:5v.handle @ jquery.min.js?v=4d4b2e4…:5
```

as you can see it fails, than i am reqestd to reload the page and the fun starts all over again.

it is weared, i delteted all my cokies cleand my databes of all password tables and removed also appconfig password *

it just starts again

**Comment by fcturner** [comment]
I fixed this last week. Now it only requires an update if the first AND second TD are not empty. 

Please try the latest master. :wink:
