### ISSUE TITLE
Share Feature Not Working - RESOLVED

### ISSUE THREAD

**Issue by mikshepard** [fcturner/passwords#178]
I just upgraded to the latest version, 18.  When I click the share button, I get a pop-up window that states "There are no users available you can share with.  LDAP is unsupported in this version".   However I'm not using LDAP, and the LDAP extension is not enabled.  

I've also tested this in two browsers (Opera and Firefox), running Owncloud 9 on Debian Jessie.  

UPDATE: Looks like Users have to be in a group for the share option to work.  If they are not in a group or in a group of just one (admin for example), they will receive that message about LDAP, regardless of LDAP being installed.

Thanks,
Mike

**Comment by fcturner** [comment]
Nope, message is just there for LDAP users. I don't know how to check for existence of LDAP, so the message always shows. 

Check the settings of the ownCloud Sharing part on the admin page; you probably have checked 'only share with users of same group' and have no other users in your group? Or did you exclude your group from sharing?

**Comment by mikshepard** [comment]
I have neither of those options you mentioned enabled.   However, for test purposes, I checked the "Restrict users to only share with users in their groups" option and then unchecked it immediately.  Now the sharing option in Passwords works as expected.  

Not sure why checking and unchecking that option worked, my sharing files with users from inside Owncloud worked fine always.  However, the problems seems to be resolved, a bug in Owncloud perhaps.  Guess we'll see if others have the same issue. 

Thanks for your help and for this amazing addition to Owncloud.  I use it daily.
-Mike

**Comment by IzK666** [comment]
It happens me too: I have to check/uncheck the "Restrict users to only share with users in their groups" in order to be able to share everyone.

**Comment by fcturner** [comment]
>Thanks for your help and for this amazing addition to Owncloud. I use it daily.

I really appreciate that, thank you.

**Comment by fcturner** [comment]
I changed the default value for the share API. But it looks like an ownCloud bug, because my app cannot and does not interfere with the share part of ownCloud.
