### ISSUE TITLE
Shared by . (Funny. Not important)

### ISSUE THREAD

**Issue by IzK666** [fcturner/passwords#179]
I was testing the sharing capabilities and it's awesome. :+1: 
After a while, I found that when the admin (my own user) share a password to anyone, the share look like: "Shared by .", without telling my name.
I have created a new user, admin too, and this was displayed fine, so that wasn't the reason.
Then I found that it happens to another user too, but in this case she wasn't an admin.
The rest of the users were fine, sharing his name correctly.

After digging a bit more I found the reason: owncloud changes. These users were created using OC 4.x, meanwhile the others was created with OC 5.x.
In this version (4.x), displayname field didn't exist. When this field was created on version 5, all the previous users got a " " (blank space) as displayname, meanwhile the new users get a NULL value.
Here is a copy from the backup of the database:
```
CREATE TABLE `oc_users` (
  `uid` varchar(64) NOT NULL DEFAULT '',
  `password` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO oc_users VALUES
("izk", "xxxxxx");
```

As I told you in the title, nothing to worry. Is easy to fix it, but useless: Not many users will be so old.... and I can fix it by myself.... if I want :laughing: I mean, change it on the database, but is fine being a ghost!

**Comment by fcturner** [comment]
Thanks! I guess I'll let it be; not many users will be updating from OC 4.x indeed.

By the way, I got the idea to change the length of 30 characters to 25 from your IzK_Tweaks :smile:
