### ISSUE TITLE
default password settings

### ISSUE THREAD

**Issue by Tealk144** [fcturner/passwords#185]
Hi,

is it possible to change the default password settings:
![a0pwo4z_700b_v1](https://cloud.githubusercontent.com/assets/12276250/14384677/97de75ce-fd9c-11e5-984c-5379a9f637ce.jpg)

**Comment by fcturner** [comment]
No, that's not possible at the moment. 
I could implement it, but I think the default should always be: everything always on. 

Can you give an example why it would be better to change the default values?

**Comment by Tealk144** [comment]
I know a lot of website which don't accept 30 character passwords or ones with special characters.
eg. one Bank allow only 5 character letters and numbers

**Comment by fcturner** [comment]
That's a horrible bank then. You can always change the 30 to 5 if you want. 

The default should still always be safe. A password with only 5 numbers and lowercase characters is horribly weak.

**Comment by Tealk144** [comment]
i will set it to 20 not to 5 oO
