### ISSUE TITLE
Arena decks occasionaly stopped filling automatically

### ISSUE THREAD

**Issue by likeyoucare** [fcturner/passwords#187]
Yesterday my arena decks stopped auto-importing. I'm playing from two PCs and a deck which I drafted from one PC didn't import on another. I tried to debug a bit and found out next that it seems Blizzard changed something. In arena.log you now can see only unique cards from your arena decklist. So if your have a deck without dublicates, your deck will be successfully auto-imported. If you have at least two copies of any card, auto-importing will fail.
Everything works fine while you drafting a fresh deck though. Haven't found out why it works yet.
You could try to catch a bug repeating next steps:
0) turn on auto-import in settings
1) draft a deck with at least two copies of any card
2) quit Hearthstone
3) delete the deck
4) start Hearthstone
5) enter arena screen

If this succeeds you probably want to delete arena.log file or try log in to your account on another PC.

**Comment by likeyoucare** [comment]
Sorry missed a window!

**Comment by fcturner** [comment]
Yeah, totally wrong place to post here. Has nothing to do with this app.
