### ISSUE TITLE
Import LastPass CSV

### ISSUE THREAD

**Issue by Draky50110** [fcturner/passwords#188]
Hello

Trying to import a CSV file exported from LastPass.

When having "File have headers", it tells me it have 456 passwords but popup error when clicking on import button asking website, username and password.

If I uncheck "File have headers", it shows me passwords preview but clicking on import button gives me error : this file contains one or more line with less than 3 columns.

Here is the content of the CSV file : http://gilles.wittezaele.fr/paste/?425cebb82552bdb4#KeqrituoxpzNnTVxg1HR3uDtmV/0BtHmzYP8GKwh7Ag

The CSV file is directly exported from LastPass.

Any idea of the problem ?

Thanks :)

**Comment by fcturner** [comment]
Not yet, but I'll look into it!

**Comment by Draky50110** [comment]
:+1:

**Comment by IzK666** [comment]
File js/script.js.
Line 2277
``var lines = contents.split('"\n');``
and line 2279
``var lines = contents.split('"\r\n');``
Requires an if (quotationMarks) sentence and search the quotation mark only if seting is checked. (but it's possible that a multiline note could fail, but I haven't tested yet)

A second error is made on line 2312
``if (!quotationMarks && lines[i].substr(0, 1) != '"') {``
should be:
``if (quotationMarks && lines[i].substr(0, 1) != '"') {``

**Comment by IzK666** [comment]
Checked: LastPass adds quotation marks only on Notes if contains more than a single line....
Can be difficult to implement.
Sample:
``url,username,password,extra,name,grouping,fav
http://twiter.com,loginname,password,,Twitter,,0``
``http://facebook.com,loginface,passface,"Long note``
``With a second line``

``And a fourth too!",Facebook,,0``
``http://gmail.com,loginmail,passmail,NOTE,Gmail,,0``

**Comment by Draky50110** [comment]
will investigate @home because FF addon can export to more than one CSV format.
Maybe export to FF format then export to another more readable for PAsswords format will work.

**Comment by IzK666** [comment]
Line 2277 should be (removed the quotation mark):
``var lines = contents.split('\n');``
Line 2279 should be (removed the quotation mark):
``var lines = contents.split('\r\n');`` 

And in line 2312:
``if (quotationMarks && lines[i].substr(0, 1) != '"') {``

With those small changes you should be able to preview the passwords that you want to import as in the next image. Red squared the changes you should change:
![preview](https://cloud.githubusercontent.com/assets/2158443/14569973/2e3f15c8-0342-11e6-9ca4-ce15a70a8aa3.PNG)

**Comment by Draky50110** [comment]
In js/script.js, I have 2277 and 2278 : 
var count = (contents.match(/\r\n/g) || []).length + 1;
var lines = contents.split('"\r\n');

And nothing on 2279 except a closing }

So what should I change ?

My full script.js : http://gilles.wittezaele.fr/paste/?8bfcd198c06a7450#ZI/RsguUWdSWZ36Hg55gKtN/Vd3uDJnEOlCx0VEQS7Y

**Comment by IzK666** [comment]
You have an old version of this file.
You have to edit lines 2275, 2277 and 2310.

After you have imported all your passwords, I recommend you to upgrade the file with the one hosted by fcturner's github (https://raw.githubusercontent.com/fcturner/passwords/master/js/script.js), otherwise you'll get this issue: #184.

**Comment by fcturner** [comment]
I'll update the master to have this fix. Thanks @IzK666

**Comment by Draky50110** [comment]
Managed to load CSV and display list of password.
I choose import button.
After few minutes, 100% imported.

But password page is "decrypting" forever and I don't see any password.
Have about 500.

By the way, maybe linked, FF addons tells me "0 logins in database".

**Comment by IzK666** [comment]
I need more details to help you. Owncloud says something in the log?

**Comment by Draky50110** [comment]
Part of log after clicking on Passwords apps on OC menu : http://gilles.wittezaele.fr/paste/?65e5d9ab97a55fc7#de/WTj4dgkLNujZ13OQbFAbJ4K4Q4UDF1i2gjlVn/Qg

**Comment by IzK666** [comment]
There is no errors in log. Just a warning.
As you said you updated the file.... don't you?

**Comment by IzK666** [comment]
Can you access to the database? Inside table oc_passwords should be all the 500 passwords you have. I recommend you to delete the last 456 passwords, which belongs to the import from lastpass, because my fix was wrong.
It can work with easy passwords (letters and numbers), but it can't handle special characters.

I apologize for my mistake. It requires more than a simple fix :cry:

**Comment by Draky50110** [comment]
No problem, will wait for a fix looking at commits ;)

**Comment by fcturner** [comment]
Hm, I will need to investigate this further.

Since this ZeroBin expires after 30 days:
```CSV
url,username,password,extra,name,grouping,fav
https://twitter.com,twitterusername,twitterpassword,,twitter.com,(empty),0
```

The ZeroBin looks really great by the way! I'll give it a try myself!

**Comment by Draky50110** [comment]
You can clic on "clone" button ;) to create

**Comment by fcturner** [comment]
Yes, running it already on my own server. Thanks! But I was looking for a pastebin replacement that lets users save a list for future reference. So now I'm working on *ownCloud Codebin* :smile:  Stay tuned!

**Comment by IzK666** [comment]
I'm here again.
Draky, I supose that you could delete the imported items from database and your passwords app is working.
I have made a small script to transform Lastpass exports into a CSV file readable by OC_Passwords.
Here is a [working url](http://izk666.github.io/LastPassConverter/)
But if you have concerns about privacy, here is [the code](https://github.com/IzK666/LastPassConverter), where you can check it, or download "index.html" and "LP.js" and run wherever you want (even offline).
As long as I tested, it works with special characters like commas, slashes and backslashes. Multiline notes are also supported.

**Comment by fcturner** [comment]
Thanks for this. I will test it too. If it works, are you okay if I implement it in my app directly?

**Comment by IzK666** [comment]
Of course you can do with this code whatever you want ;)
But I have in mind to improve the reading capabilities of csv files, and not only optimized for LastPass. It shouldn't take me too much time....

**Comment by fcturner** [comment]
Great, then I'll wait for that.

**Comment by Draky50110** [comment]
Ok, have tested.
First : all seems ok as it outputs me a CSV file with " inside.

Problem to test : I previously deactivated then uninstalled apps.
Then, in PHPMyAdmin, I deleted the 3 MySQL tables about OC_Passwords.

Today, I uploaded master.zip from source code, then unzipped, then renamed to passwords directory in apps.
I enabled it in OC Apps... but it didn't re-create MySQL tables so when launching the app, it tells me about categories and passwords not being loaded...

I don't know how to install it back properly :(

**Comment by fcturner** [comment]
That's odd, give that CREATE and OVERWRITE are both 'true' in [appinfo/database.xml](https://github.com/fcturner/passwords/blob/master/appinfo/database.xml). 

Can you deactivate, reload the page and activate the app again? Seems like an ownCloud bug. 
You can ultimately use PHPmyadmin to create the tables for you, with the info from the above file.

**Comment by fcturner** [comment]
I mean, you can download and use my appinfo/database.xml to load into your PHPMyAdmin. It has an import function.

**Comment by Draky50110** [comment]
My PMA can"t import your XML file, even if I change value like *db*prefix* to oc_ as in my database.
0 tables created.

**Comment by fcturner** [comment]
http://stackoverflow.com/a/31258098

**Comment by fcturner** [comment]
Does PMA give an error?

**Comment by fcturner** [comment]
@Draky50110 Run this SQL in PHPMyAdmin. It will create the tables like there are created by ownCloud. The query below is an export of my own PHPMyAdmin.

```sql
CREATE TABLE IF NOT EXISTS oc_passwords (
    id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id VARCHAR(500) COLLATE UTF8_BIN NOT NULL DEFAULT '',
    loginname VARCHAR(500) COLLATE UTF8_BIN DEFAULT NULL,
    website VARCHAR(500) COLLATE UTF8_BIN NOT NULL DEFAULT '',
    address VARCHAR(1000) COLLATE UTF8_BIN DEFAULT NULL,
    pass BLOB NOT NULL,
    properties BLOB,
    notes BLOB,
    creation_date DATE NOT NULL,
    deleted TINYINT(1) NOT NULL DEFAULT '0',
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS oc_passwords_categories (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  user_id varchar(500) COLLATE utf8_bin NOT NULL DEFAULT '',
  category_name varchar(1000) COLLATE utf8_bin NOT NULL DEFAULT '',
  category_colour varchar(6) COLLATE utf8_bin NOT NULL DEFAULT 'eeeeee',
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS oc_passwords_share (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  pwid bigint(20) unsigned DEFAULT NULL,
  sharedto varchar(500) COLLATE utf8_bin DEFAULT NULL,
  sharekey varchar(64) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (id)
);
```

**Comment by fcturner** [comment]
@IzK666 Any news on your new LastPass plugin?

**Comment by Draky50110** [comment]
347 passwords imported successfully.
Takes AGES to decrypt...

Giving up.

**Comment by fcturner** [comment]
Pease don't! :cry:
So the import works and the decryption time is not related to the LastPass import function?

Are you running ownCloud on a Raspberry 1 or 2 or a similar simple computer?

**Comment by fcturner** [comment]
@IzK666 Would you like to create a Pull Request with your code in your LP.js to implement it in my script.js? Thanks!

This can be closed.

**Comment by IzK666** [comment]
:sweat: I'll have ready for this weekend.

**Comment by fcturner** [comment]
Don't stress to much :wink:

**Comment by Happyfeet01** [comment]
i have the same issue as @Draky50110 download the latest zip from Github and export the lastpass csv file.

"error : this file contains one or more line with less than 3 columns" so i can´t start the import.

**Comment by fcturner** [comment]
Can you post the file with fake values but the same structure? Then I can test it too.

**Comment by Happyfeet01** [comment]
my problem is solved. I edit the exported file with an texteditor because some wrong lines. Then the upload works good, I must also delete the lines with secure notes entrys.
