### ISSUE TITLE
Share button missing when I try to change sharing

### ISSUE THREAD

**Issue by benedikt-d** [fcturner/passwords#190]
When I try to change the sharing of my password and add other people I can't find the share button. 

Console is also throwing an error:

`jquery.min.js?v=ca99676…:4 Uncaught Error: Syntax error, unrecognized expression: #new_value_popup input[value=max.mueller]`

**Comment by benedikt-d** [comment]
I did a test when there is no dot in the username that I share i with it works. Javascript is having trouble with my usernames that are like this: "firstname.lastname"

**Comment by fcturner** [comment]
Yes, I see. 
I'll fix this, thanks for letting me know!

**Comment by fcturner** [comment]
Fixed this following http://learn.jquery.com/using-jquery-core/faq/how-do-i-select-an-element-by-an-id-that-has-characters-used-in-css-notation/.
jQuery cannot select elements with periods and other CSS-characters.

You can download the master if you want this fixed immediately.

**Comment by fcturner** [comment]
Hm, not fixed at all.
Please stand by :smile:

**Comment by fcturner** [comment]
I got an error with a username that contained a `@` too. Now fixed for all.

**Comment by benedikt-d** [comment]
Works perfectly! Thanks a lot!

**Comment by fcturner** [comment]
:+1:
