### ISSUE TITLE
copy button doesn't work for shared password

### ISSUE THREAD

**Issue by Timo3** [fcturner/passwords#191]

**Comment by Timo3** [comment]
tested on uptodate versions of Chrome, Firefox and IE 11

**Comment by Timo3** [comment]
seems like it doesn't work for non shared password as well

**Comment by fcturner** [comment]
I will check this, thanks!

**Comment by DovendyrE** [comment]
Can confirm this for owncloud 9.0
Just installed owncloud 9.0.2 and the copy password function is working again.
Have not tested shared passwords.

**Comment by fcturner** [comment]
How does it not work? Do you get a prompt with the password instead of the header text that the password has been copied?
Or doesn't it work at all?

**Comment by Timo3** [comment]
Hi,
It displays the copy button but I can’t click on it. I’m on owncloud 9.0

**Comment by DovendyrE** [comment]
Same in 9.0.2, it displays edit and copy, you can click edit, but not copy.. Going to upgrade another owncloud instance tomorrow. Will provide feedback from that upgrade when its done.

**Comment by DovendyrE** [comment]
Now I have tested the upgrade to 9.0.2 on 2 new servers.. On the one running on ubuntu LTS 14.04 with ondrej updated php (PHP 5.6.20-1+deb.sury.org) the copy password button works. The other servers have ubuntu 15.10 with php 5.6.11 and did not work. Upgraded one of them to php7.0.4 and ubuntu 16.04 but not working there either..
All serveres have owncloud 9.0.2 and passwords 18.1 (cloned from git today).

**Comment by fcturner** [comment]
Now that's an unexpected outcome... Thanks for your research!

I guess it's time to look for another library.

**Comment by fcturner** [comment]
Please download latest master; this should be fixed now.

**Comment by fcturner** [comment]
This will be released when v19 is ready (working on LDAP support at the moment). Thanks for your time!
