### ISSUE TITLE
New Chrome extension

### ISSUE THREAD

**Issue by thefirstofthe300** [fcturner/passwords#192]
So I am sad to say that I am not going to be able to get my Chrome extension going.  I was going to have it be my first real project but I now realize that I am not one who thinks in a way conducive to writing good code and understanding the more abstract concepts of coding.  I have only gotten a few functions in in about a week and I am still stuck trying to understand how the chrome extension API works (too much going on that I am just not grasping).  On top of these issues, I am starting to look for my first job and I don't need anything else hanging over my head.

If anyone else gets an extension going, feel free to ping me for bug testing.  Believe me, I am extremely willing to help out in such a respect.  However, I cannot in good conscience keep holding this project back because of a lack of an extension for the most popular browser in the world.

**Comment by fcturner** [comment]
Alright, I see. Thank you for your hard work! Can you send me the code you've made so far, or a place where I can find it?

**Comment by thefirstofthe300** [comment]
github.com/thefirstofthe300/ownCloud-Passwords

**Comment by fcturner** [comment]
:+1:
