### ISSUE TITLE
Password API issues

### ISSUE THREAD

**Issue by marcelschmidt1337** [fcturner/passwords#197]
Hi, I've started to play around with the REST api of your plugin trying to build a simple mobile app for this and found several issues there:

1. Basic user auth + password request not only gives me all passwords of this user but also gives me objects of all other existing users (see example below)

2. The creation date key seems to always show "1970-01-01"

3. The properties key seems to be broken, shouldn't it be a nested object anyway? ~~Otherwise this would be hard to deserialize (or am I missing something at this point?)~~ **UPDATE: I wrote a workaround for this in my code.**

4. Why is the "deleted" key not a bool?

5. "loginname" and "address" (both outside the "properties") always seem to be empty and the "notes" bool doesn't seem to change either.

This is what I get as response (I've changed the other user names):

[{
	"id": 27,
	"user_id": "TestREST",
	"loginname": "",
	"website": "copter.com",
	"address": "",
	"pass": "S9Dn6)_(f@P4$b%WK-d,62_2m9aZwM",
	"properties": "\"loginname\" : \"Nope\", \"address\" : \"http:\/\/lol.info\", \"strength\" : \"97\", \"length\" : \"30\", \"lower\" : \"1\", \"upper\" : \"1\", \"number\" : \"1\", \"special\" : \"1\", \"category\" : \"0\", \"datechanged\" : \"2016-05-12\", \"notes\" : \"rofl\", \"sharekey\" : \"dc395d50934e5d03cae0d99d0f75c575f6083dba697e9d61f160d9f1e89a08ed\", \"sharedwith\" : \"\"",
	"notes": false,
	"creation_date": "1970-01-01",
	"deleted": "1"
}, {
	"id": 25,
	"user_id": "TestREST",
	"loginname": "",
	"website": "example.com",
	"address": "",
	"pass": "c3N2+\u003E]R6%2&%}*ASshtpP97zgUZ+3",
	"properties": "\"loginname\" : \"TestUser\", \"address\" : \"http:\/\/example.com\", \"strength\" : \"101\", \"length\" : \"30\", \"lower\" : \"1\", \"upper\" : \"1\", \"number\" : \"1\", \"special\" : \"1\", \"category\" : \"1\", \"datechanged\" : \"2016-05-12\", \"notes\" : \"TestNote\", \"sharekey\" : \"6a8c0434e0cbd97949ed9a2e8588406a9f95e91f8ff81d6db0ee34a8f1a5f3f3\", \"sharedwith\" : \"\"",
	"notes": false,
	"creation_date": "1970-01-01",
	"deleted": "0"
}, {
	"id": 26,
	"user_id": "TestREST",
	"loginname": "",
	"website": "example2.org",
	"address": "",
	"pass": "jn5~?vN7Z4e.6tD#Z{7J$b%P(&3Zz7",
	"properties": "\"loginname\" : \"Bla\", \"address\" : \"http:\/\/example2.org\", \"strength\" : \"97\", \"length\" : \"30\", \"lower\" : \"1\", \"upper\" : \"1\", \"number\" : \"1\", \"special\" : \"1\", \"category\" : \"2\", \"datechanged\" : \"2016-05-12\", \"notes\" : \"my notes\", \"sharekey\" : \"59fe5f15abe5e7c6e565949de8ddbba523d1fc2c017eb7d60749d08f7c666774\", \"sharedwith\" : \"\"",
	"notes": false,
	"creation_date": "1970-01-01",
	"deleted": "0"
}, {
	"id": 0,
	"user_id": "OtherUser1",
	"loginname": null,
	"website": "OtherUser1",
	"address": null,
	"pass": false,
	"properties": false,
	"notes": false,
	"creation_date": null,
	"deleted": null
}, {
	"id": 0,
	"user_id": "OtherUser2",
	"loginname": null,
	"website": "OtherUser2",
	"address": null,
	"pass": false,
	"properties": false,
	"notes": false,
	"creation_date": null,
	"deleted": null
}, {
	"id": 0,
	"user_id": "TestREST",
	"loginname": null,
	"website": "TestREST",
	"address": null,
	"pass": false,
	"properties": false,
	"notes": false,
	"creation_date": null,
	"deleted": null
}]

**Comment by fcturner** [comment]
Thanks, I'll look into this!

**Comment by fcturner** [comment]
>Basic user auth + password request not only gives me all passwords of this user but also gives me objects of all other existing users (see example below)

That's odd, should be that way -> bug

>The creation date key seems to always show "1970-01-01"

Intended, backwards compatibility with versions prior to v17. The real date is now under `properties`.

The properties key seems to be broken, shouldn't it be a nested object anyway? Otherwise this would be hard to deserialize (or am I missing something at this point?) UPDATE: I wrote a workaround for this in my code.

>Nope, just JSON created with javascript. Thanks for the workaround.

Why is the "deleted" key not a bool?

>Support for other databases. INT(1) is fine and works as well as BOOL.

"loginname" and "address" (both outside the "properties") always seem to be empty and the "notes" bool doesn't seem to change either.

>Same as for date; backwards compatibility with versions prior to v17. Should be empty.

**Comment by fcturner** [comment]
Besides, as for why `deleted` is a bool:
```xml
<field>
	<name>deleted</name>
	<type>boolean</type>
	<default>0</default>
	<notnull>true</notnull>
</field>
```
Don't ask me, I defined it as such in [/appinfo/database.xml](https://github.com/fcturner/passwords/blob/master/appinfo/database.xml). Your own backend might be translating it differently.

**Comment by fcturner** [comment]
I guess this can be closed. Please reopen issue if you still experience problems.
