### ISSUE TITLE
Add additional field for notes, free comments or something like this for free text

### ISSUE THREAD

**Issue by fcturner** [fcturner/passwords#20]
By ArnDoran @ https://apps.owncloud.com/content/show.php/Passwords?content=170480

**Comment by godfuture** [comment]
As this password manager could be used for any application, I highly support this feature request. And even for websites, notes might be useful. +1

**Comment by fcturner** [comment]
What do you think of labels? Would that be good enough to you @godfuture?

**Comment by IzK666** [comment]
Hi!

I was thinking about this suggested notes field, and how to add to the app.

My idea is to add it a clickable icon (notepad icon?) when a password has a note attached and view it in a small popup like users and passwords do. This icon can be placed between passwords and strength columns.

What do you think?

**Comment by fcturner** [comment]
I think that might not be user friendly enough.

People who want to use notes, would like to see them at once I guess. So, I was thinking more of a CSS-overflow thing to show the first 100 px or so.

Besides that, I would like labels to appear on the left side in the navigation pane. I wanted to add the column `label_id` to the existing table, and create another table (`oc_passwords_labels` for instance), to register the labels to passwords:

label_id | label_name
------------ | -------------
1 | Work 
2 | Home
3 | Me
4 | My wife

What do you think?

**Comment by Tramour** [comment]
I second both your proposals because they do not exclude each other.  Labels are nice to categorize things but notes are more special and comped of more words. Thus I want them both.

**Comment by Tramour** [comment]
Damn that autocorrection: composed not comped...

**Comment by glegarand** [comment]
Notes could be useful, but password groups would be even more useful to me (ie. one group for each of my customers).
Passwords, password groups or even the whole passwords of a user sharing would be great too.

**Comment by fcturner** [comment]
This is implemented in 8.0.7: #47
