### ISSUE TITLE
Can't create category via REST

### ISSUE THREAD

**Issue by marcelschmidt1337** [fcturner/passwords#202]
I can't create a new category via REST: I've tried your example from the wiki page and POST this Json to the API (https://[owncloud]/index.php/apps/passwords/api/0.1/categories):

{
    "category_name": "My category",
    "category_colour": "aa0000"
}

I'm always getting a "false" as a response and the category isn't created.

**Comment by fcturner** [comment]
Thanks for reporting! I'll look into this.

**Comment by fcturner** [comment]
Fixed it for SQLite, it contained an old error. 
So if you are using SQLite, please try again with latest master.

**Comment by marcelschmidt1337** [comment]
Thanks for the fix, can you do it for MySQL and the other databases, too?

**Comment by fcturner** [comment]
Please download the latest master ([:package:zip](../archive/master.zip) or [:package:tarball](../archive/master.tar.gz)). It should be fixed now.
