### ISSUE TITLE
says mcrypt libraries not available but are installed.

### ISSUE THREAD

**Issue by snapek** [fcturner/passwords#204]
I'm trying to get this working on an Ubuntu 14.04 Owncloud VM, and have updated and installed mcrypt  but passwords still says mcrypt libraries are not available and I can not enable the app in Owncloud.

Am I missing an obvious step here?

**Comment by fcturner** [comment]
Did you install php5-mcrypt?

If so,

sudo php5enmod mcrypt

And then:

sudo service apache2 restart 

might help.

**Comment by fcturner** [comment]
What those two commands do is this: the 1st line is enabling module named 'mcrypt', and then restart apache2 to update the config. You can see the enabled module from /etc/apache2/mods-available.

**Comment by snapek** [comment]
Yeah I double checked and php5-mcrypt was installed, but it's not listed in the enabled modules in /etc/apache2/mods-available.

I also tried explicitly doing a 'php5enmod mcrypt' and restarted apache2, but still not in mods-available.

This may be an issue specific to Ubuntu 14.04 I guess???

**Comment by fcturner** [comment]
Yes, but I run 14.04 too. Have you googled for 'Ubuntu 14.04 install mcrypt'?

**Comment by snapek** [comment]
I had google, albeit not exactly that query, and the vast majority of the instructions indicate php5enmod mcrypt then restarting apache2 should be sufficient.

That said, that step was not resulting in it being in mods-available.

One guide pointed out that if it was not showing up, to symlink the mcrypt.ini into mods-available (ln -sf ../conf.d/mcrypt.ini while in /etc/apache2/mods-available) and restart.  This has worked and I can enable Passwords now.

Thanks! :)

**Comment by fcturner** [comment]
Great!!
