### ISSUE TITLE
Edit password idea

### ISSUE THREAD

**Issue by Vebryn** [fcturner/passwords#208]
Hi,

Another idea about your awesome app :)

In order to edit a password, we have to click on each element we want to edit. What about to add a button next others in password row? Edit action will fill the add window and "Add password" button will be changed to "Edit password".

With this update, each row element can direclty be clicked and copied into clipboard :)

Advantages:
* Only 1 click to copy a row element
* Only 2 clicks to edit all row element

Best regards

**Comment by fcturner** [comment]
I'll remember it for v19. Thanks for the idea!
