### ISSUE TITLE
Master Password or Re-auth when switching to password app

### ISSUE THREAD

**Issue by annunaki2k2** [fcturner/passwords#209]
Just discovered your passwords app, and it is awesome - well done, and keep up the great work!

I do, however, have one idea that I would really like it if it could be implemented: When switching to the password app in Owncloud in the browser, I'd like an option to be asked to re-authenticate (to prove it is me) or, perhaps instead, be prompted for a separate "master" password that is not the same one used to authenticate into Owncloud in the first place. There could also be a configurable time-out that means if you keep switching between Owncloud apps, you don't have to keep re-authenticating, so long as you authenticated within the past X minutes.

My reason is simple (and I suspect others have the same): I keep Owncloud open in my browser for long periods of time, specifically to keep the calendar visible, but also just because I use it so much. At the moment, if I do that (and I have to leave my desk for whatever reason), then it is very simple for anyone to switch to the passwords app and steal my passwords without my knowledge. Sure, they're will be arguments that you should always lock your screen etc. (which I do anyway), but it's an Xscreensaver - easily killed with root privileges, and working in an IT department means most people have those.

I'm not sure, based on your architecture, how easy this would be to implement, but I hope you consider it as a good idea, and I look forward to testing it in the near future.

**Comment by fcturner** [comment]
Well, I see the need for such a thing. Maybe I could just check the time stamp of the login cookie with plain JavaScript. 

A master password is also a very good idea, but it would mean that I create something for existing users so their password will be re-encrypted with the new master password. Tough job, but great idea!!

**Comment by annunaki2k2** [comment]
Glad you like the idea.

If you start work on it, I'll be very happy to help with testing.

**Comment by fcturner** [comment]
:+1:

**Comment by fcturner** [comment]
Almost done here, will create a pull request tomorrow, which you can test.

**Comment by annunaki2k2** [comment]
Wow - incredibly quick turn around on this one; amazing!

As promised, I want to help testing this one, so I've pulled the branch down and had a quick go with it.

First note is that, on the authenticate prompt, for some reason I can't just press <Enter> once I've typed my password, I have to instead click the "Continue" button. Is this deliberate, or perhaps an oversight? (Tested in Owncloud 9.0.2, on Firefox 38.1/46.0, and Vivaldi 1.2.485).

The second thing is that I don't seem to be able to use my owncloud password to authenticate, it just says "This password is invalid. Please try again."

I have found the following log entry from owncloud:
`{PHP} Undefined index: token at /var/www/annunaki2k2.co.uk/htdocs/owncloud/apps/passwords/templates/main.php#28`
which I presume has something to do with it. Do i need to run some sort of upgrade script to add tables to the database?

**Comment by fcturner** [comment]
Thanks!!!

I only implemented master passwords yet, ownCloud passwords is work in progress, but will be finished soon. Then the PHP error will be gone too. 

Nice one on the Enter key, I'll add that.

**Comment by fcturner** [comment]
No, no database changes. I had that at first, but then I thought that it would be quicker to let master passwords be saved as a user setting. It now saves to oc_preferences with 'master_password' as config value.

**Comment by fcturner** [comment]
(Hashed with 512-bit strong SHA-2)

**Comment by annunaki2k2** [comment]
I've now set a master password and have been using it today. No major problems found so far, and for something this fundamental to have been implemented so quickly, this is awesome - seriously well done!

The only thing that I've noticed that could be considered a bug is the `This can be changed in your settings.` link on the "Authenticate" prompt is directing me to the root of my web server rather than to the virtual directory of "/owncloud", so you might want to check that.

Other than that, I have a couple of ideas/suggestions that you perhaps could add to round this off:
* The ability to press enter - as previously mentioned.
* Perhaps add an option that, when the "require password" option is set, the inactivity timer can be configured to lock the app again instead of logging you off?
* Would it be possible to have the authentication valid for N number of seconds/minutes? At the moment when switching from the password app, to quickly do something else in owncloud, and then switching back, it will always need re-authing with the password. Perhaps valid authentication can be cached for 5 minutes (but make that option/time-out configurable?).

Excellent job and keep-up the great work!

**Comment by fcturner** [comment]
>link on the "Authenticate" prompt is directing me to the root

Fixed!
>The ability to press enter - as previously mentioned.

Implemented!
>Perhaps add an option that, when the "require password" option is set, the inactivity timer can be configured to lock the app again instead of logging you off?

Implemented!

>Would it be possible to have the authentication valid for N number of seconds/minutes?

That's hard. I think I like it this way. If you forget to get back to the Passwords immediately, you still risk your passwords.

**Comment by fcturner** [comment]
I changed the working of this completely. Now there's a new `Auth` class, so user passwords will work too. I have it tested locally, still need to upload it. But there will be no more tokens in the URL, everything will be tested server-side (safer).

**Comment by fcturner** [comment]
Uploaded, please test again: https://github.com/fcturner/passwords/archive/add-masterpassword.zip

**Comment by annunaki2k2** [comment]
Truly incredible work - well done!

I see that, despite your previous reservations, you even managed add the "Stay authorised for" timer idea too - brilliant :-)

I have had a good play with it now, and I have a new list of possible problems/glitches that I've come across. In no particular order:
* When switching from "Master password" to "ownCloud password", you're prompted to "Enter old master password", which I did, followed by \<Enter\> - but that didin't work, I instead had to click the "Authorize" Button manually - I suggest you should be able to just press the enter key here.
* After dismissing "The master password has been removed" message, the "Enter old master password" prompt still remained, but I expected this to disappear.
* When switching between the "ownCloud Password" & "No extra password" options, is it possible to request a re-auth of the ownCloud password again? If not, it's pretty easy for anyone to deactivate the owncloud password requirement, view/copy passwords, then re-enable the feature, and you wouldn't even know.
* I seemed to have occasional (it didn't happen every-time) what appear to be random page reloads when switching into the password app or to the user preferences, which I never experienced before. I'm not sure what was going on here, perhaps there is something JS related that's causing a reload of the page to be triggered before it had finished loading (timer related?). I wondered if I was me being too impatient when switching between the user-prefs and then to the password app, but even if I went to another app first and then onto the password app, it would sometimes still happen.
* When the lock count down reaches zero, you receive a "You will be logged off due to in-activity" dialogue box, but perhaps there should be no prompt at all, and you just return the "Enter your password " prompt.
* I couldn't pin down the exact combination of events that caused it, but occasionally, whilst changing settings (I think specifically the "Stay authorised for" timer setting), I would receive "Error whilst saving field auth_timer!" error notifications. These seem to reflect the following message also appearing in the log: "{PHP} Undefined index: oc_passwords_auth at /var/www/annunaki2k2.co.uk/htdocs/owncloud"/apps/passwords/templates/main.php#29

**Comment by e-alfred** [comment]
I would also second this feature. I have Owncloud open most of the time with other apps and if I open the passwords app it logs me out after some time is pretty annoying. If it gets locked with a master password after a short inactivity it would be far more convenient that the situation as it is now.

**Comment by e-alfred** [comment]
Maybe the secure containers app could help you design something using a master password?

Link here: https://github.com/delight-software-gmbh/oc_SecureContainer

**Comment by fcturner** [comment]
I'm already done implementing this. I'll upload it today.

**Comment by annunaki2k2** [comment]
@fcturner: Just wanted to check if you managed to take a look at the items I noted above?

**Comment by fcturner** [comment]
@annunaki2k2 Yes, fixed them all. Thanks for them! I will upload the new version tonight in a new pull request. 
(Many things changed).

**Comment by annunaki2k2** [comment]
@fcturner Awesome - look forward to testing it again! :-)
