### ISSUE TITLE
postgres UNION

### ISSUE THREAD

**Issue by mtahiue** [fcturner/passwords#211]
Hi many thanks for your contribution

I've done a fresh owncloud install, with postgres db

I've added password apps from github master, freshly pulled from repo

When loading the app in oc , there is an error 500

Logs says  :

`"message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'SELECT id, user_id, loginname, website, address, pass, properties, notes, creation_date, deleted FROM oc_passwords WHERE user_id = ? OR id IN (SELECT pwid FROM oc_passwords_share WHERE sharedto = ?) UNION ALL SELECT  uid as id, CASE WHEN displayname IS NULL THEN uid ELSE displayname END as user_id, NULL as loginname, uid as website, NULL as address, NULL as pass, NULL as properties, NULL as notes, NULL as creation_date, NULL as deleted FROM oc_users ORDER BY LOWER(website) ASC' with params [\\\"user\\\", \\\"user\\\"]:\\n\\nSQLSTATE[42804]: Datatype mismatch: 7 ERROR:  UNION types bigint and character varying cannot be matched\\nLINE 1: ...ords_share WHERE sharedto = $2) UNION ALL SELECT  uid as id,...\\n                                                             ^\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractPostgreSQLDriver-`

**Comment by fcturner** [comment]
Hey, I might be able to make it possible again. Stay tuned!

**Comment by fcturner** [comment]
See #161

**Comment by fcturner** [comment]
By the way, how did you enable this app? It is unsupported for PostGreSQL (for now) and ownCloud should block the enabling because of that...

**Comment by abishai** [comment]
I tried passwords today to find pgsql is not supported. Is it hard to implement support or it's just a lack of interest? I doubt querries are complex, however I not looked into the code.

**Comment by fcturner** [comment]
No, absolutely not a lack of interest. My interest is in the interest of my users. So, if you think it's relevant, then I do too.

Query's *are* the reasons it is not working. I need to relate and combine some tables and MySQL, SQlite and PostgreSQL aren't much alike, I'm afraid.

But! I've updated the master with a possible fix. Would you like to test this @abishai @mtahiue ?

**Comment by abishai** [comment]
You can't use expressions in ORDER BY if you use UNION under postgreSQL. You must wrap it.
SELECT x1.* FROM (SELECT UNION SELECT) ORDER BY LOWER()

**Comment by abishai** [comment]
select x1.id, x1.user_id, x1.loginname, x1.website, x1.address, x1.pass, x1.properties, x1.notes, x1.creation_date, x1.deleted  FROM 
(SELECT CAST(id AS CHAR) AS id, user_id, loginname, LOWER(website) as website, address, pass, properties, notes, creation_date, deleted 
FROM oc_passwords WHERE user_id = ? OR id IN (SELECT pwid FROM oc_passwords_share WHERE sharedto = ?) 

UNION ALL 
SELECT uid AS id, CASE WHEN displayname IS NULL THEN uid ELSE displayname END AS user_id, NULL AS loginname, LOWER(uid) AS website, NULL AS address, NULL AS pass, NULL AS properties, NULL AS notes, NULL AS creation_date, NULL AS deleted FROM oc_users ) x1
ORDER BY LOWER(website) ASC

**Comment by abishai** [comment]
Or split complex query to 2 and merge it in php side.

**Comment by abishai** [comment]
Hmmm, I fixed query locally and added some passwords, however I see no passwords when I open app.

$result has data, however $arr after json decode-encode is null.
Data is 
array(4) {
  [0]=>
  object(OCA\Passwords\Db\Password)#1966 (12) {
    ["id"]=>
    int(0)
    ["loginname":protected]=>
    NULL
    ["website":protected]=>
    string(7) "abishai"
    ["address":protected]=>
    NULL
    ["pass":protected]=>
    NULL
    ["properties":protected]=>
    NULL
    ["notes":protected]=>
    NULL
    ["userId":protected]=>
    string(7) "abishai"
    ["creationDate":protected]=>
    NULL
    ["deleted":protected]=>
    NULL
    ["_updatedFields":"OCP\AppFramework\Db\Entity":private]=>
    array(0) {
    }
    ["_fieldTypes":"OCP\AppFramework\Db\Entity":private]=>
    array(1) {
      ["id"]=>
      string(7) "integer"
    }
  }
  [1]=>
  object(OCA\Passwords\Db\Password)#1967 (12) {
    ["id"]=>
    int(0)
    ["loginname":protected]=>
    NULL
    ["website":protected]=>
    string(4) "root"
    ["address":protected]=>
    NULL
    ["pass":protected]=>
    NULL
    ["properties":protected]=>
    NULL
    ["notes":protected]=>
    NULL
    ["userId":protected]=>
    string(4) "root"
    ["creationDate":protected]=>
    NULL
    ["deleted":protected]=>
    NULL
    ["_updatedFields":"OCP\AppFramework\Db\Entity":private]=>
    array(0) {
    }
    ["_fieldTypes":"OCP\AppFramework\Db\Entity":private]=>
    array(1) {
      ["id"]=>
      string(7) "integer"
    }
  }
  [2]=>
  object(OCA\Passwords\Db\Password)#1970 (12) {
    ["id"]=>
    int(2)
    ["loginname":protected]=>
    string(0) ""
    ["website":protected]=>
    string(4) "test"
    ["address":protected]=>
    string(0) ""
    ["pass":protected]=>
    resource(41) of type (stream)
    ["properties":protected]=>
    resource(42) of type (stream)
    ["notes":protected]=>
    resource(43) of type (stream)
    ["userId":protected]=>
    string(4) "root"
    ["creationDate":protected]=>
    string(10) "1970-01-01"
    ["deleted":protected]=>
    bool(false)
    ["_updatedFields":"OCP\AppFramework\Db\Entity":private]=>
    array(0) {
    }
    ["_fieldTypes":"OCP\AppFramework\Db\Entity":private]=>
    array(1) {
      ["id"]=>
      string(7) "integer"
    }
  }
  [3]=>
  object(OCA\Passwords\Db\Password)#1971 (12) {
    ["id"]=>
    int(1)
    ["loginname":protected]=>
    string(0) ""
    ["website":protected]=>
    string(8) "test.com"
    ["address":protected]=>
    string(0) ""
    ["pass":protected]=>
    resource(44) of type (stream)
    ["properties":protected]=>
    resource(45) of type (stream)
    ["notes":protected]=>
    resource(46) of type (stream)
    ["userId":protected]=>
    string(4) "root"
    ["creationDate":protected]=>
    string(10) "1970-01-01"
    ["deleted":protected]=>
    bool(false)
    ["_updatedFields":"OCP\AppFramework\Db\Entity":private]=>
    array(0) {
    }
    ["_fieldTypes":"OCP\AppFramework\Db\Entity":private]=>
    array(1) {
      ["id"]=>
      string(7) "integer"
    }
  }
}

**Comment by fcturner** [comment]
Please update to latest beta: https://github.com/fcturner/passwords/archive/v19.zip
I changed the query, please try it :wink:

**Comment by abishai** [comment]
Thank you!
Query is working now, at least application opens without errors, however I see no passwords. The root of the problem is json_decode(json_encode) in passwordservice.php. The input $result I posted above, the output $arr is NULL.

**Comment by fcturner** [comment]
I see, but that's when the database connection has been closed. So it might be PHP related. Are you on PHP 7? I didn't test that. But will be if I must :wink:

**Comment by abishai** [comment]
Nope, php56.

**Comment by abishai** [comment]
Should I open new bug report?

**Comment by abishai** [comment]
Actually, I don't understand why you use so strange construction. You already have an array of objects - you can just iterate it in foreach()

**Comment by fcturner** [comment]
Well, I created that last year and I worked well back then :wink: 
I'm not a professional IT man, just a microbiologist with a hobby.

No, we'll fix it within this issue, because I *think* it is PHP related, but I'm not sure.

Can you post a suggestion with `foreach()`?

**Comment by fcturner** [comment]
I'm always open to new and better alternatives!

**Comment by fcturner** [comment]
Found this here:
http://php.net/manual/en/function.json-encode.php

*Notice the last json_decode does not working :) ,you need to use a variable to use the encoded data in json_decode():-*

```php
<?php
$arr=array('a'=>1,'b'=>2,'c'=>3,'d'=>4,'e'=>5);

echo json_encode($arr)."<br />";
//{"a":1,"b":2,"c":3,"d":4,"e":5}

print_r (json_decode(json_encode($arr)));
//stdClass Object ( [a] => 1 [b] => 2 [c] => 3 [d] => 4 [e] => 5 )
echo "<br />";
$var=json_encode($arr);
print_r (json_decode($var,true));
//Array ( [a] => 1 [b] => 2 [c] => 3 [d] => 4 [e] => 5 )
echo "<br />";
print_r (json_decode(json_encode($arr)),true);//no output
?>
```

**Comment by abishai** [comment]
json_encode() return false
json_last_error returns JSON_ERROR_UNSUPPORTED_TYPE

**Comment by fcturner** [comment]
Maybe the encode is not needed on the output of a PostgreSQL dump.

Can you try again if you edit the original 
```php
$arr = json_decode(json_encode($result), true);
```
to
```php
$arr = json_decode($result, true);
```
?

**Comment by abishai** [comment]
I don't think so. Can you check the type of notes or pass after query? Mine have 'stream'

**Comment by abishai** [comment]
Hey, but the fields are blobs!
			<field>
				<name>notes</name>
				<type>blob</type>
				<notnull>false</notnull>
			</field>

**Comment by fcturner** [comment]
Yes, they are. Does that matter? It prevents easy download of encrypted strings, since there are binary. 

It all works perfectly on MySQL, MariaSB and SQLite...

**Comment by abishai** [comment]
Are blob fields has stream values in case of mysql or sqlite?
["pass":protected]=>
resource(44) of type (stream)

type stream breaks json_encode()

**Comment by fcturner** [comment]
From https://wiki.postgresql.org/wiki/BinaryFilesInDB:

>Caveat: many people come to this page looking for PostgreSQL's equivalent of the MySLQ "BLOB*" data types. The equivalent in Postgres is BYTEA. For details on PostgreSQL's "binary large object" (which are quite different from MySQL BLOB's and provide random seeking, etc), see below.

**Comment by fcturner** [comment]
PostgreSQL might be the most advanced database, it surely is the least interchangeable and approachable database. Horrible for app developers really, and painfully reminds me of MS Internet Explorer. 

Could you alter your password database tables to a VARCHAR(5000) format and see if that works?

**Comment by abishai** [comment]
How to force application to create database tables again? I removed tables, however after disable-enable they are not re-created.

**Comment by abishai** [comment]
OK, found it. Removed related stuff from appconfig table. 
character varying instead of bytea worked. Actually, I see no reasons to use bytea. It's a blob-type and the blobs are slightly different datatypes then common ones.

**Comment by fcturner** [comment]
So if I define te columns as TEXT in my database file then PostgreSQL works? I don't need `bytea` (or `blob` as MySQL calls it) necessarily.
I could write an `ALTER TABLE` on next update, so users don't have to delete all app settings, like:
```sql
ALTER TABLE oc_passwords 
    ALTER COLUMN pass TYPE varchar(3000),
    ALTER COLUMN properties TYPE varchar(3000),
    ALTER COLUMN notes TYPE varchar(3000); 
```
Would that work? Can you check that?

**Comment by abishai** [comment]
You can do this, bytea can be normally casted to varchar

**Comment by fcturner** [comment]
But does my app now works on PostgreSQL as expected after this database change? Then we don't need to look further for a pgsql fix.

**Comment by abishai** [comment]
Well, I created test password and it was shown in the interface. I think, yes, pgsql support works.

**Comment by fcturner** [comment]
👍👍👍👍

**Comment by fcturner** [comment]
Thanks for all your work!!! Really, really helpful to other pgsql users!

**Comment by abishai** [comment]
BTW, do you have plans to support NextCloud ? Now it shares the same codebase with Owncloud, but that not for long.

**Comment by fcturner** [comment]
I hadn't had heard of it, so I looked it up. 
Really seems like a divorce within ownCloud, splitting up in ownCloud and NextCloud, with Frank Karlitschek as main ownCloud antagonist. It really made me think of OpenOffice and LibreOffice. 

I'll tell you what; I don't like the way this man communicates and interacts with other app developers like me. So, I was rather glad to read about his exit. Still, if NextCloud will mature like LibreOffice did after their split with OpenOffice, I will surely support NextCloud. But for now, let them show us first what they're worth and present the benefits. But if the software and its developers will be as 'German' as with ownCloud (which I don't like, no offence intended, it's just their culture), I don't see the need to support NextCloud too. 

We'll see!

**Comment by abishai** [comment]
Sure thing, let's see. However, now NextCloud devs GPL'd all enterprise stuff of Owncloud (for example password protected directory with upload (sic!) support). I think, they have a good starting point.

**Comment by abishai** [comment]
I enable ZM debug, and noticed that ZMNinja sends strange POST request before it starts to output event - it passes empy eventid.

```
06/18/16 12:15:52.168494 zms[100220].DB1-zm_logger.cpp/234 [LogOpts: level=DB9/DB9, screen=OFF, database=OFF, logfile=DB9->/var/log/zoneminder/zm_debug.log.31565, syslog=INF]
06/18/16 12:15:52.168781 zms[100220].DB1-zm_utils.cpp/262 [Detected a x86\x86-64 processor with SSSE3]
06/18/16 12:15:52.168807 zms[100220].DB1-zms.cpp/102 [Query: source=event&mode=jpeg&event=&frame=1&replay=single&rate=100&connkey=515832&scale=100&auth=a306d89941daf860e3685311737e350b]
06/18/16 12:15:52.168869 zms[100220].DB1-zm_user.cpp/172 [Attempting to authenticate user from auth string 'a306d89941daf860e3685311737e350b']
06/18/16 12:15:52.169318 zms[100220].DB1-zm_user.cpp/235 [Checking auth_key '...Change me to something unique...admin*4ACFE3202A5FF5CF467898FC58AAB1D61502944110.0.0.112185116' -> auth_md5 'a306d89941daf860e3685311737e350b']
06/18/16 12:15:52.169335 zms[100220].DB1-zm_user.cpp/241 [Authenticated user 'admin']
06/18/16 12:15:52.170326 zms[100220].FAT-zm_event.cpp/756 [Unable to load event 0, not found in DB]

06/18/16 12:15:52.507772 zms[100220].DB1-zm_logger.cpp/234 [LogOpts: level=DB9/DB9, screen=OFF, database=OFF, logfile=DB9->/var/log/zoneminder/zm_debug.log.31566, syslog=INF]
06/18/16 12:15:52.508011 zms[100220].DB1-zm_utils.cpp/262 [Detected a x86\x86-64 processor with SSSE3]
06/18/16 12:15:52.508036 zms[100220].DB1-zms.cpp/102 [Query: source=event&mode=jpeg&event=12257&frame=1&replay=single&rate=100&connkey=515832&scale=100&auth=a306d89941daf860e3685311737e350b]
06/18/16 12:15:52.508061 zms[100220].DB1-zm_user.cpp/172 [Attempting to authenticate user from auth string 'a306d89941daf860e3685311737e350b']
06/18/16 12:15:52.508539 zms[100220].DB1-zm_user.cpp/235 [Checking auth_key '...Change me to something unique...admin*4ACFE3202A5FF5CF467898FC58AAB1D61502944110.0.0.112185116' -> auth_md5 'a306d89941daf860e3685311737e350b']
06/18/16 12:15:52.508556 zms[100220].DB1-zm_user.cpp/241 [Authenticated user 'admin']
06/18/16 12:15:52.509499 zms[100220].DB3-zm_stream.cpp/70 [FPS:6.24, MXFPS:10.00, BFPS:6.24, EFPS:6.24, FM:1]
06/18/16 12:15:52.509522 zms[100220].DB3-zm_stream.cpp/77 [aEFPS:6.24, aFM:1]
06/18/16 12:15:52.510029 zms[100220].DB2-zm_event.cpp/859 [Event:12257, Frames:61, Duration: 9.77]
06/18/16 12:15:52.510518 zms[100220].DB4-zm_db.cpp/89 [Success running query: select Id, Name, ServerId, Type, Function+0, Enabled, LinkedMonitors, Device, Channel, Format, V4LMultiBuffer, V4LCapturesPerFrame, Protocol, Method, Host, Port, Path, Options, User, Pass, Width, Height, Colours, Palette, Orientation+0, Deinterlacing, RTSPDescribe, Brightness, Contrast, Hue, Colour, EventPrefix, LabelFormat, LabelX, LabelY, LabelSize, ImageBufferCount, WarmupCount, PreEventCount, PostEventCount, StreamReplayBuffer, AlarmFrameCount, SectionLength, FrameSkip, MotionFrameSkip, AnalysisFPS, AnalysisUpdateDelay, MaxFPS, AlarmMaxFPS, FPSReportInterval, RefBlendPerc, AlarmRefBlendPerc, TrackMotion, SignalCheckColour, Exif from Monitors where Id = 5]
```
Not related to original bug report, but curious.

**Comment by mtahiue** [comment]
Hi

I've tested on my side, password app pulled @c3a16b3cad2381145aa5faf1edd5f7d094a0fe18

I've disabled the app, removed the oc_password tables
and cleaned appconfig table to remove password entries.

then i re enabled the app.

i also tried with the alter mentionned above

and  i still have psql issues : 


```Message\":\"An exception occurred while executing 'SELECT CAST(id AS CHAR) AS id, user_id, loginname, website, address, pass, properties, notes, creation_date, deleted FROM oc_passwords WHERE user_id = ? OR id IN (SELECT pwid FROM oc_passwords_share WHERE sharedto = ?) UNION ALL SELECT  uid AS id, CASE WHEN displayname IS NULL THEN uid ELSE displayname END AS user_id, NULL AS loginname, uid AS website, NULL AS address, NULL AS pass, NULL AS properties, NULL AS notes, NULL AS creation_date, NULL AS deleted FROM oc_users ORDER BY LOWER(website) ASC' with params [\\\"user\\\", \\\"user\\\"]:\\n\\nSQLSTATE[0A000]: Feature not supported: 7 ERROR:  invalid UNION\\\/INTERSECT\\\/EXCEPT ORDER BY clause\\nLINE 1: ...tion_date, NULL AS deleted FROM oc_users ORDER BY LOWER(webs...\\n                                                             ^\\nDETAIL:  Only result column names can be used, not expressions or functions.\\nHINT:  Add the expression\\\/function to every SELECT, or move the UNION into a FROM clause.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(175): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOPgSql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT CAST(id ...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/statementwrapper.php(75): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\\/v```

Hope this help

**Comment by fcturner** [comment]
The part of your error `HINT: Add the expression/function to every SELECT, or move the UNION into a FROM clause.` is exactly what I did [here](https://github.com/fcturner/passwords/blob/v19/db/passwordmapper.php#L62-L63):
```sql
// fix for PostgreSQL, cannot use UNION and ORDER BY in same query hierarchy
$sql = 'SELECT * FROM (' . $sql . ') AS t1';
```
So that (and the fact that it works for abishai) makes me think that you didn't use the latest v19 version (which is to be released, as we're testing this as we speak). Would you like to test that version?

URL for zip: https://github.com/fcturner/passwords/archive/v19.zip
URL for tarball: https://github.com/fcturner/passwords/archive/v19.tar.gz

**Comment by mtahiue** [comment]
latest v19 version works like a charm  on postgres, congrats to @fcturner and @abishai thanks

**Comment by fcturner** [comment]
Cool! Thanks for reporting and testing! :+1:
