### ISSUE TITLE
App doesn't seem to work in a second app path

### ISSUE THREAD

**Issue by intirix** [fcturner/passwords#214]
I have a second app path set up.  I install 3rd party apps, like this one, into the 2nd app path to make upgrading easier.  I get 404's for all the static resources for this app, however.  Stylesheets and images don't show up.  This makes the user interface unusable.  I can work around the issue by installing the password app directly into the main apps folder.

  array (
    0 => 
    array (
      'path' => '/var/www/html/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/apps',
      'url' => '/apps2',
      'writable' => true,
    ),
  ),

https://doc.owncloud.org/server/8.0/developer_manual/core/configfile.html

**Comment by fcturner** [comment]
Great addition, never thought of it. 

The solution is simple, I'll fix this for the release of version 19.
