### ISSUE TITLE
JS error when changing category for password that hasn't been shared

### ISSUE THREAD

**Issue by intirix** [fcturner/passwords#215]
I created a new password without a category.  I was unable to change the category after the fact.  I kept getting a Javascript error when hitting the Save button.  The code is related to sharing.  I shared the password with someone else and was able to change the category.

script.js?v=9be3e84…:131 Uncaught TypeError: Cannot read property 'split' of undefinedPasswords.updateActive @ script.js?v=9be3e84…:131(anonymous function) @ script.js?v=9be3e84…:712x.event.dispatch @ jquery.min.js?v=9be3e84…:5v.handle @ jquery.min.js?v=9be3e84…:5

			updateActive: function(index, loginname, website, address, pass, notes, sharewith, category, deleted, changedDate) {
				
				var sharewithArr = [];
				if ($.isArray(sharewith)) {
					sharewithArr = sharewith;
				} else {
					sharewithArr = sharewith.split(', ');
				}

sharewith is null, so the code throws a null pointer exception

**Comment by fcturner** [comment]
Thanks! I'll fix that too.

**Comment by fcturner** [comment]
This has already been fixed in the master, forgot that. Please download the master. It will be in next release.
ZIP: https://github.com/fcturner/passwords/archive/master.zip
Tarball: https://github.com/fcturner/passwords/archive/master.tar.gz
```js
var sharewithArr = [];
if ($.isArray(sharewith)) {
	sharewithArr = sharewith;
} else if (!sharewith) {
	sharewithArr = "";
} else {
	sharewithArr = sharewith.split(', ');
}
```

**Comment by intirix** [comment]
I verified that this is fixed in master, thanks

**Comment by fcturner** [comment]
:+1:
