### ISSUE TITLE
Help: Database errors

### ISSUE THREAD

**Issue by crazyman143** [fcturner/passwords#216]
Hi, 

I'm hoping someone can help me as I really want to use this app. I have downloaded the latest release and copied the contents to /var/www/cloud/apps/passwords (my directory was previously changed from 'owncloud' to 'cloud') on my ubuntu server. I enabled the app but I can only get "Error: Could not load passwords." when loading it. In the logs I see what look to be database errors. Here's a snippet of one: `Exception: {"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'SELECT id, user_id, loginname, website, address, pass, properties, notes, creation_date, deleted FROM oc_passwords WHERE user_id = ? OR id IN (SELECT pwid FROM oc_passwords_share WHERE sharedto = ?) UNION ALL SELECT DISTINCT displaynames.uid as id, displaynames.displayname as user_id, NULL as loginname, displaynames.uid as website, NULL as address, NULL as pass, NULL as properties, NULL as notes, NULL as creation_date, NULL as deleted FROM oc_group_user AS users LEFT JOIN (SELECT uid, CASE WHEN displayname IS NULL THEN uid ELSE displayname END AS displayname FROM oc_users) AS displaynames ON users.uid = displaynames.uid WHERE gid IN (SELECT DISTINCT gid FROM oc_group_user WHERE uid = ?) ORDER BY LOWER(website) ASC':\n\nSQLSTATE[HY000]: General error: 1 1st ORDER BY term does not match any column in the result set","Code":0,"Trace":"#0 \/var\/www\/cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116):`

Hope someone here can help me. Thanks!

**Comment by fcturner** [comment]
Hello, thanks for wanting to use my app! I tell you what: this will work for you in an instant. I will keep supporting you until it works.

First: I think you're using SQLite. In that case, the line `ORDER BY LOWER(website) ASC` does not work. I fixed this some weeks ago, but you are presumably using my latest release. I haven't released that fix yet.
You have two options:
  1. Use the master version which includes the fix: [zip-file](https://github.com/fcturner/passwords/archive/master.zip) or [tar.gz-file](https://github.com/fcturner/passwords/archive/master.tar.gz).
  2. Edit the lines that causes your error: here for the passwords: https://github.com/fcturner/passwords/commit/5a87a87a0787c3eb398e5490b265d051bc377ecd and here for the categories: https://github.com/fcturner/passwords/commit/aa0e9d52894210291b514e563b9170fb6045e9f2

I will release this fix (and some others) this week, along with a great new function: master password authentication.

**Comment by crazyman143** [comment]
Beautiful! That was an easy fix. Thanks so much for the help. Looking forward to using this.
