### ISSUE TITLE
InvalidArgumentException: Identifier "OCP\IL10N" is not defined

### ISSUE THREAD

**Issue by Scurz** [fcturner/passwords#219]
Hi,

When trying to install password, I get this error :
InvalidArgumentException: Identifier "OCP\IL10N" is not defined

Owncloud version : ownCloud 7.0.4+dfsg-4~deb8u4 (Debian) (stable)

Thank you

**Comment by fcturner** [comment]
ownCloud 7 is not supported and should be blocked for enabling by ownCloud itself. How come you were able to enable it?

**Comment by Scurz** [comment]
I downloaded the package and moved it to /usr/share/owncloud/apps.

Thank you for your help.

**Comment by fcturner** [comment]
Well, you're welcome, but haven't you read my post? Your ownCloud version IS NOT SUPPORTED, so please update to ownCloud version 8 or 9.

**Comment by fcturner** [comment]
Apps still need to be enabled in ownCloud, and it should check for the minimum supported version, which it apparently didn't.
