### ISSUE TITLE
App blocks access when using SSL extensions and subdomain rerouting

### ISSUE THREAD

**Issue by Tramour** [fcturner/passwords#22]
My hoster "all inkl "provides a ssl extension so I do not need an own ssl-certificate.
Thus my subdomain is rerouted via https://ssl-account.com/[...] Unfortunately this is not detected by your app and the "access blocked" screen appears.

Any ideas?

**Comment by fcturner** [comment]
When entering the app, `templates\main.php` tests for a secure connection with the function `IsSecure` (line 10):
````php
return
	(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
	|| $_SERVER['SERVER_PORT'] == 443
````
It returns `true` if 
- `$_SERVER['HTTPS']` is not empty **AND** `$_SERVER['HTTPS']` is not off,

**OR**
- `$_SERVER['SERVER_PORT']` is equal to port `443`

So your server does not meet either of these requirements. You can circumvent this test by adding `return true;` after line 3 in `templates\main.php`. So change:
````php
function isSecure() {
	$url = 'http://' . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];
````
to
````php
function isSecure() {
	return true;
	$url = 'http://' . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];
````
Of course, I *highly* discourage this, but if you trust your SSL extension, this might be your fix.

Would you like to let me know if this works for you? I cannot think of another option for now.

**Comment by fcturner** [comment]
This is fixed by https://github.com/fcturner/passwords/commit/e0ca88e343fe8d500517205f1a05ec23226cc60e.

(assuming you have `forcessl => true` in your `config.php` which you should with SSL extensions)

Would you like to check this @Tramour? The master contains this new edit.
