### ISSUE TITLE
One library uses HTML-syntaxed JS

### ISSUE THREAD

**Issue by viki53** [fcturner/passwords#220]
I was just checking out the code, PHP and JS all together and I just saw some very dirty HTML in the JS, like `<font>` tags in `js/sorttable.js`.

This plugin is from 2007, so maybe it should be updated (there might be something more efficient by now, with the new HTML5 APIs) or at leat modified to use valid HTML.

I might have a go at it if I find some time in the next few days/weeks, but I wanted to let everyone know, in case somebody was bored enough to do it…

**Comment by fcturner** [comment]
The library `sorttable.js` is indeed very old. As is it working fine, I don't see an immediate reason to change or replace this library. I didn't even change [the source code](http://www.kryogenix.org/code/browser/sorttable/). If it works well already now, replacement would only improve [aesthetics](https://en.wikipedia.org/wiki/Aesthetics). 

I appreciate that you would like to take the time to investigate other options. Please open a new issue if you've found something worth implementing. :+1:
