### ISSUE TITLE
insertShare

### ISSUE THREAD

**Issue by mtahiue** [fcturner/passwords#223]
Hi

Maybe and error on insertShare 

insert with NULL
https://github.com/fcturner/passwords/blob/v19/db/passwordmapper.php#L83

but  table says NOT NULL
https://github.com/fcturner/passwords/blob/v19/appinfo/database.xml#L119

**Comment by mtahiue** [comment]
fixed by altering table : 

ALTER TABLE oc_passwords_share ALTER COLUMN id set  DEFAULT nextval('oc_passwords_share_id_seq');

**Comment by fcturner** [comment]
No, I believe you're wrong. `NULL` on an auto-increment column means: auto-increment.
https://github.com/fcturner/passwords/blob/v19/appinfo/database.xml#L120

`nextval` is a horrible sequence manipulation function. The database should work on its own, and it should never be needed to increment an ID by yourself with a function. That's a way of database managing you should always avoid.

Besides, it works fine.
