### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by kuzmichus** [fcturner/passwords#225]
I use branch v19, When I try to add a new password, nothing happens in the log the following errors:

`Error 	PHP 	Invalid argument supplied for foreach() at /usr/share/webapps/owncloud/apps/passwords/service/passwordservice.php#28 	2016-06-22T14:40:50+00:00
Error 	PHP 	Uninitialized string offset: 0 at /usr/share/webapps/owncloud/apps/passwords/service/passwordservice.php#364 	2016-06-22T14:40:49+00:00
Error 	PHP 	Uninitialized string offset: 0 at /usr/share/webapps/owncloud/apps/passwords/service/passwordservice.php#364 	2016-06-22T14:40:49+00:00
Error	PHP	Uninitialized string offset: 0 at /usr/share/webapps/owncloud/apps/passwords/service/passwordservice.php#364	2016-06-22T14:40:49+00:00
Error	PHP	Invalid argument supplied for foreach() at /usr/share/webapps/owncloud/apps/passwords/service/passwordservice.php#28	2016-06-22T14:40:27+00:00
`
PHP7

**Comment by fcturner** [comment]
That's odd, never heard of it before. What version of ownCloud are you using? And what version of PHP?

**Comment by fcturner** [comment]
The error is on the last line of:
```php
$result = $this->mapper->findAll($userId);
$arr_enc = json_encode($result);
$arr = json_decode($arr_enc, true);

$serverKey = \OC::$server->getConfig()->getSystemValue('passwordsalt', '');

foreach ($arr as $row => $value) {
```

**Comment by peregrinphp** [comment]
OwnCloud version: 9.0.2.2
PHP: 7.0.8

**Comment by fcturner** [comment]
I can't reproduce this :cry:

**Comment by fcturner** [comment]
Do you get this error only when you create **the first password**? 
It doesn't happen when you have already **at least 1** password in your list (or trash)?

**Comment by kuzmichus** [comment]
Yes, i tried to create the first password.
I cant create any password.

**Comment by fcturner** [comment]
Please download the latest master ([zip](../archive/master.zip) or [tarball](../archive/master.tar.gz)). It should be fixed now.

**Comment by fcturner** [comment]
Is this still a problem on the latest master?

**Comment by kuzmichus** [comment]
Fixed in master, thank you.
