### ISSUE TITLE
no login with #-char in password

### ISSUE THREAD

**Issue by omocinteractive** [fcturner/passwords#227]
hi,
i tried to login in the app, but nothing happens. at the moment, i use owncloud without a ssl-certifikation for testing, so could see the request - the password was cut after the #char.kind regards, after i changed the password, everything was okay.
andreas

**Comment by fcturner** [comment]
Thank you for catching that one! I thus need to escape HTML characters. Can you confirm this by having a '<' or '>' character in your password? I should lead to an error too.

**Comment by omocinteractive** [comment]
... you are right - the same error:

Password: test<>#1234

Result (POST-Request):

http://owncloud.omoc.de/index.php/apps/passwords/auth/test%3C%3E

**Comment by Onlyodin** [comment]
Is there a chance of committing a fix for this to the master/19-beta? Since OC 9.1 I'm now without passwords.

**Comment by fcturner** [comment]
Quickest for now is to set the user value `extra_auth_type` for passwords to `none`.
Values are in oc_appconfig.

Will that work for you?

**Comment by fcturner** [comment]
I'm very sorry you can't use my app right now!

**Comment by fcturner** [comment]
Or temporarily edit your password in settings.

**Comment by Onlyodin** [comment]
After figuring out you were referring to the database table and not a config file (my bad), I inserted a row into oc_appconfig with 'passwords','extra_auth_type','none', but this did not work.

I then figured because you said user value, it must be user specific, so I eventually found oc_preferences and inserted the above values for the necessary userid's and passwords is now functional again.

**Comment by Onlyodin** [comment]
For the benefit of anyone with this problem and multiple users, this query will insert a user preference for each user to set extra_auth_type to none:

`insert into oc_preferences (userid,appid,configkey,configvalue) select distinct(userid),'passwords','extra_auth_type','none' from oc_preferences;`

**Comment by omocinteractive** [comment]
... can be closed :)

**Comment by fcturner** [comment]
Fixed with #243
