### ISSUE TITLE
Add notification to passwords app in webinterface if version is outdated

### ISSUE THREAD

**Issue by e-alfred** [fcturner/passwords#228]
Hello,

as you don't use the Owncloud app store it would be great to let users know if their version of the passwords app is outdated. This could be done by showing a notification in the passwords app webinterface.

**Comment by fcturner** [comment]
I think I could make that work. Thanks for the idea!

**Comment by fcturner** [comment]
Implemented in master!

**Comment by fcturner** [comment]
Just go to ownCloud/NextCloud admin page, and you'll be notified under 'Passwords'.
