### ISSUE TITLE
Uninstalling passwords plugin

### ISSUE THREAD

**Issue by Vebryn** [fcturner/passwords#229]
Hi,

I'm looking to uninstall password plugin.

I found a "disable" button into admin panel. I also found 3 tables into oc database : oc_passwords, oc_passwords_categories and oc_passwords_share. Finally, there is the passwords dir.

Is there anything else ?

Thank you,

Best regards.

**Comment by fcturner** [comment]
Hello! Too bad you're uninstalling my app. Want to share why?

Yes, it only consists of these three database tables and the passwords folder in /apps.

**Comment by Vebryn** [comment]
Unfortunately, my 200+ entries takes too long to manipulate through my web-browser. It also consumes to many memory. So I revert to my keepass database. Nevertheless, I'm still watching on passwords plugin :)

**Comment by fcturner** [comment]
I think I cannot change that easily, as decryption takes some time. But I need to look for a way every password decrypts only on click, so it doesn't need to decrypt everything on page load. 
Stay tuned!
