### ISSUE TITLE
Initial login/password entry not working for LDAP users (v19 beta)

### ISSUE THREAD

**Issue by jfmchivall** [fcturner/passwords#230]
I have ownCloud 8.2.6 using the LDAP backend for authentication

I installed the passwords app using git clone, ending up with the current master (v19 Beta) installed. After activating the app it asks for the user's ownCloud login password before proceeding (is this the master password feature?). Correctly entering the password results in "Incorrect password" message. I assume this is due to LDAP authentication not being properly supported.

v18.0 works OK as it does not initially ask for the login password allowing the app to be used.

**Comment by fcturner** [comment]
True, LDAP is not supported. I will turn it off when LDAP is used, until I figured out how to support it.
