### ISSUE TITLE
Incompatible with OC 9.1

### ISSUE THREAD

**Issue by viki53** [fcturner/passwords#231]
Hi,

I just installed OwnCloud 9.1, which deactivated most of my apps.

When I tried to activate `Passwords`, I got this error:
> ownCloud 9.0 or lower is required.

Is there any way you can update the config file to allow higher versions (such as `9.1` or even `9.x`)?

Thanks a lot!

**Comment by polcape** [comment]
I have modified appinfo/info.xml, setting `max-version="9.1"/>`
and re-enbale the apps via occ (php occ app:enable passwords) and works fine.

**Comment by viki53** [comment]
Yup, I did the same.

But this should be done automatically for everyone, instead of having to access the server manually.

**Comment by fcturner** [comment]
Yes, I needed to check whether my code would work on OC 9.1. On 8.1, everything broke.

I will edit the info so it will install. Thanks!

**Comment by viki53** [comment]
Seems to work fine on my instance. So that's that. ;-)

**Comment by fcturner** [comment]
Already solved in master.
