### ISSUE TITLE
hung on "Decrypting passwords...."

### ISSUE THREAD

**Issue by rborel** [fcturner/passwords#235]
After import of 200+ passwords, when the page loads it stays hung on "Decrypting passwords...".   It stays there past the timeout set for the user.  I've increased the timeout to over 3 minutes and it still doesn't finish.  If I click on the "Active Passwords" in the upper left, the entries show up but I can't view/edit them due to the "Decrypting passwords..." message.  I've truncated the data tables and re-imported a couple times...  My firefox connector also cannot pull the passwords in.

Ideas?

**Comment by fcturner** [comment]
Does the owncloud log tell you anything?

**Comment by rborel** [comment]
Looking now...  additional info... browser doesn't seem to make a difference...

**Comment by fcturner** [comment]
It's not your browser, it's a bug. 

Which version of Passwords are you using?

**Comment by rborel** [comment]
v19-beta1

**Comment by fcturner** [comment]
Thanks. Log entries?

**Comment by rborel** [comment]
Nothing sticking out...  Still looking.. My log's over 700m (guess I should purge more often...)

**Comment by rborel** [comment]
I've tested...  if this helps..
1. Truncated the data in oc_passwords
2. added a single entry from the import
Results:
works fine..

[nextcloud.txt](https://github.com/fcturner/passwords/files/378854/nextcloud.txt)

**Comment by rborel** [comment]
Reading that... it is not resolved..  What I was trying to say was that a single entry from the import does not cause the hang.

**Comment by rborel** [comment]
I've increased the logging to debug and still nothing additional in the nextcloud.log

**Comment by rborel** [comment]
Let me know if there's anything you need me to test/do... I'm in IT, feel your pain and if no one else is going to say it... passwords rocks... I've removed keepass2 from everywhere and switched over..

**Comment by fcturner** [comment]
😄 Thank you! Great compliments 👍 👍 👍

**Comment by fcturner** [comment]
So, can you try to import 50 at first?

**Comment by rborel** [comment]
50 worked fine.  Problem seems to kick in between 100-108.  Ok,  Did the import leaving off the 'notes' and 'url' fields.  Works fine.  Going to look at the data and see what may be corrupt.  Funny thing is before the v19 update it seemed to work.

**Comment by rborel** [comment]
Ok, definitely something in my 'notes' section.  Digging through the data now to see what.

**Comment by rborel** [comment]
Haven't found anything.  Imported the 360 passwords without the notes.  I have the export and will be adding back the notes one at a time.  When I hit what did it I'll let you know...

**Comment by rborel** [comment]
Ok, back to thinking it's a bug...  It seems to happen when there are a lot of data rows with entries in the 'notes' field.

**Comment by tmaex** [comment]
Same Problem here:
Passwords is keeping "decrypting"

Undefined variable: only_share_with_own_group at ***/apps/passwords/db/passwordmapper.php#75 is all I can find in the log.

**Comment by rborel** [comment]
Just updated from git... doesn't seem to be resolved.

**Comment by fcturner** [comment]
I'm not that fast! 😄 I didn't import the fix yet.
Just update now, and please report back.

**Comment by fcturner** [comment]
@tmaex Thanks!!

**Comment by rborel** [comment]
lol

**Comment by rborel** [comment]
c'mon you sleeping or something???

**Comment by rborel** [comment]
Looks good...  Imported fine.

**Comment by fcturner** [comment]
In the UK it's 12:50 PM now, time for my boss to keep me busy 😉

**Comment by fcturner** [comment]
Great!

**Comment by rborel** [comment]
At this point I'm going to have to say bug killed...  decrypted, opened and all 'notes' are in tact...  Thank you for maintaining and being so responsive.  Really.  Great addon to Next and ownCloud...

**Comment by tmaex** [comment]
@rborel next time you need to get things extra quick you could just change git origin to the fork or download it from the fork on github.

@fcturner you're welcome!

**Comment by rborel** [comment]
Thanks... I need to learn git a bit more...  Again.. thanks to all contributing.

**Comment by fcturner** [comment]
👍
