### ISSUE TITLE
Master password doesn't work with special characters

### ISSUE THREAD

**Issue by intheloft** [fcturner/passwords#236]
If you have a special character in the master password for example ? or & you are locked out as the password doesn't get encoded before injected into the URL request.

A simple edit to auth.js fixes this by adding encodeURIComponent(...) around the pass variable

	Auth.prototype = {
		checkAuth: function(pass, type) {
			var result = 'error';
			var request = $.ajax({
				url: this._baseUrl + '/' + encodeURIComponent(pass) + '/' + type,
				method: 'POST',
				async: false
			});

Is it safe to send passwords in a URL variable? Wouldn't it be better in the POST data instead?

**Comment by fcturner** [comment]
Thanks!! This solves #227 too. 

Can you do a code suggestion on a POST solution? I'm always willing to learn.

**Comment by intheloft** [comment]
Thinking about it, I would definitely NOT send passwords encoded in the URL in a get request as they will be stored and show up in logs on the server (and possible on the clients logs/history depending on their settings) which totally defeats the point of having any encryption on the passwords.

You can send POST data just by tweaking the method you have already been using and passing it through the data parameter json encoded. I'm not sure what url you'd need to send it to as I have barely looked through the code (only to fix the bug I found)

Then you'd need to tweak the PHP code a bit to get the data from the POST variable rather than encoded in the URL but that will be pretty straight forward.
 
       Auth.prototype = {
            checkAuth: function(pass, type) {
                var result = 'error';
                var request = $.ajax({
                    url: this._baseUrl + '/auth',
                    data: { password : pass, authtype : type},
                    method: 'POST',
                    async: false
                });

**Comment by fcturner** [comment]
Thanks, I'll implement this asap.

**Comment by omocinteractive** [comment]
thx!!!

**Comment by fcturner** [comment]
I got it! Now uploading to git!

**Comment by fcturner** [comment]
Done!
