### ISSUE TITLE
Migrate from passman?

### ISSUE THREAD

**Issue by psych0d0g** [fcturner/passwords#238]
i want to know if it is possible to migrate to passwords from passman?

**Comment by fcturner** [comment]
Sure, must be a way. Does PassMan have an export function, like saving everything to a CSV file?
Or else, are the passwords encrypted in the database? If not, you can export them there (this however will never work on my app, way too strong encryption).

**Comment by IzK666** [comment]
PassMan hasn't any export function and all passwords are encrypted in DB. There is no easy way to migrate anything.

PS: I'm back after a while.... Sorry for my disappearence. :wink:
My old PSU was faulty with random shutdowns and took me long to know what happens.

**Comment by fcturner** [comment]
Then the answer is no 😞 

You could contact the developers of PassMan. 
Although PassMan is totally out of development.

**Comment by fcturner** [comment]
@IzK666 Welcome back!
