### ISSUE TITLE
table oc_passwords already exists

### ISSUE THREAD

**Issue by psych0d0g** [fcturner/passwords#239]
i tried to activate passwords and get mysql errors because oc_passwords table already exists:

root@webserver:/var/www/cloud# sudo -u www-data php occ app:enable passwords

  [Doctrine\DBAL\Exception\TableExistsException]
  An exception occurred while executing 'CREATE TABLE `oc_passwords` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `user_id` VARCHAR(500) DEFAULT '' NOT NULL, `logi
  nname` VARCHAR(500) DEFAULT NULL, `website` VARCHAR(500) DEFAULT '' NOT NULL, `address` VARCHAR(1000) DEFAULT NULL, `pass` VARCHAR(3000) NOT NULL, `properties` VAR
  CHAR(3000) DEFAULT NULL, `notes` VARCHAR(3000) DEFAULT NULL, `creation_date` DATE NOT NULL, `deleted` TINYINT(1) DEFAULT '0' NOT NULL, PRIMARY KEY(`id`)) DEFAULT C
  HARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_passwords' already exists

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_passwords' already exists

  [PDOException]
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_passwords' already exists

**Comment by fcturner** [comment]
This is due to existence of an app called PassMan which uses the same database table like you said in #238, so it's not a bug. 

Let's fix this in #238.
