### ISSUE TITLE
browser add-in not working since last git pull

### ISSUE THREAD

**Issue by rborel** [fcturner/passwords#242]
The update that fixed the 'Hung on Decrypting' issue seems to have broken the browser addin.

**Comment by fcturner** [comment]
That's strange, but I don't support the addin. @eglia - Any ideas?

**Comment by eglia** [comment]
This should be fixed with v0.3.4 of the Firefox addon. The problem is if the app fails to decrypt/parse the properties of an entry, the API will just return properties: false instead of an object. I added an additional check & a warning for this case.

**Comment by rborel** [comment]
It appears to be fixed.   Thank you guys for your efforts on this
project.   Just need an android client..   Users...   Never satisfied....
;)

**Comment by intirix** [comment]
@rborel Working on it ;)
