### ISSUE TITLE
Only show users with Passwords enabled on the share dialog

### ISSUE THREAD

**Issue by webmarka** [fcturner/passwords#244]
This is a feature request proposal. Being able to restrict the users list which appear on the share dialog box would be great! 

For example, only show users who have rights to access to a certain group. Or users who are in the group assigned to the Password app.

Being able to hide the user name (and only show the display name) would be another feature I'd like to have.

**Comment by fcturner** [comment]
> Being able to restrict the users list which appear on the share dialog box would be great! For example, only show users who have rights to access to a certain group. Or users who are in the group assigned to the Password app.

I did this; it looks up users who are in the same user's group. When you change the ownCloud admin settings, this will be changed in Passwords too.

> Being able to hide the user name (and only show the display name) would be another feature I'd like to have.

That's a good suggestion. What about users who don't have a display name? And what do you think about **always** hiding the username when a display name is available? So it won't become a setting, just a simple code change.

**Comment by fcturner** [comment]
> Being able to hide the user name (and only show the display name) would be another feature I'd like to have.

> > That's a good suggestion. What about users who don't have a display name? And what do you think about **always** hiding the username when a display name is available? So it won't become a setting, just a simple code change.

Implemented: https://github.com/fcturner/passwords/commit/ae1005a95e83332d3306d2a437894a4bbedffbbf

**Comment by webmarka** [comment]
> I did this; it looks up users who are in the same user's group. When you change the ownCloud admin settings and on the Users page, this will be changed in Passwords too.

Shame on me, I just realized that for the group restriction feature, the option "Restrict users to only share with users in their groups" has to be checked in the Admin settings!! Now it works as expected!

Another little CSS thing about the share dialog : when a user has a profile picture, we don't see it. The CSS declaration should be changed to something like : 

`#popupContent img {
...
		width: 98%;
}`

Instead of width: 4%;

**Comment by fcturner** [comment]
Thanks! I opened a new issue for that.
