### ISSUE TITLE
Password has Number indicator is incorrect.

### ISSUE THREAD

**Issue by intirix** [fcturner/passwords#247]
https://github.com/fcturner/passwords/blob/master/service/passwordservice.php
Line 128 and 129 both use Calculations::strhasspecial.  This is causing the Number indicator to be the same as the Special indicator.  Reported by @lzK666 to the Android app.

https://github.com/intirix/cloudpasswordmanager/issues/2

**Comment by fcturner** [comment]
Thanks! I fixed it: https://github.com/fcturner/passwords/commit/c249d72432a43f204e842e15122c62897a24d0b3
