### ISSUE TITLE
info.xml needs to be updated to max-version="10.0"

### ISSUE THREAD

**Issue by seraphyn** [fcturner/passwords#249]
In case for using passwords in nextcloud, appinfo/info.xml should be updated to 
`        <owncloud min-version="8.0" max-version="10.0"/>`

**Comment by fcturner** [comment]
Thanks! I will.

**Comment by fcturner** [comment]
Although NextCloud should read from a <nextcloud> attribute, not an <owncloud> attribute.

**Comment by fcturner** [comment]
Huh? I typed "a 'nextcloud' attribute, not an 'owncloud' attribute".

**Comment by nbourdais** [comment]
You can have both attributes, I have tested on master ( v19-beta3) and nextcloud 10.0  : 
```
<owncloud min-version="8.0" max-version="9.1"/>
<nextcloud min-version="8.0" max-version="10.0"/>
```
and it works

**Comment by fcturner** [comment]
Done!
