### ISSUE TITLE
Cannot enable app: not supported html files error message

### ISSUE THREAD

**Issue by pepprim** [fcturner/passwords#250]
Hi,

I'm trying to install the latest release of Passwords app in a fresh install of Owncloud 9.0.4. I did a direct download of the zip file in the releases page and upladoed manually by ftp to my Owncloud instance.

When I try to enable the app through the web interface I get this message:

     "Archives of type text/html are not supported"

I deleted de .md files (readme, authors and changelog), just in case, but as I already expected it didn't work. Neither I didn't find any html file in the app directories.

**Comment by fcturner** [comment]
Hello! Thanks for using my app! Remember that the master version has some exciting new features on top of the last release (like extra authentication using a master password), albeit being still a beta.

I think you uploaded the zip file to your server. You should upload the extracted folder after you rename it to 'passwords'.

**Comment by fcturner** [comment]
Link to the master (beta) version:
https://github.com/fcturner/passwords/archive/master.zip

It offers support for NextCloud and PostGreSQL too.

**Comment by pepprim** [comment]
Thanks for your reply @fcturner, and thanks for share your work. I hope I can resolve this problem and use your appication. It looks awesome.

Yes, I extracted the folder and renamed it before uploading. About version, I didn't download the latest master... I mean, I downloaded the 18.0 release  from the releases page. Should I go with the previous release, 17.2?

**Comment by fcturner** [comment]
No, that's not the point. Version 18 is fine (and stable). 

I thought about this; are you activating the app on the `Tools` subpage or the `Not activated` subpage? You need the `Not activated` subpage; the other one will try to download and extract my app from the ownCloud App Store, which I refuse to support due to privacy concerns (read more about this in the [installation part of the readme](https://github.com/fcturner/passwords#installation).

**Comment by pepprim** [comment]
>  thought about this; are you activating the app on the Tools subpage or the Not activated subpage? You need the Not activated subpage; the other one will try to download and extract my app from the ownCloud App Store

Yes! Exactly that, was the problem. Thanks for your help @fcturner!

**Comment by fcturner** [comment]
Great!!! I wish you the best using this app. Whenever you run into trouble, feel free to contact me again.
