### ISSUE TITLE
Sharing not working with Postgres 9.5.4

### ISSUE THREAD

**Issue by kbaegis** [fcturner/passwords#256]
The interface allows you to "share passwords", but on logging in the shared passwords are not populated.

**Comment by fcturner** [comment]
When you login as the user who shared the password, does the icon show how many users you've shared the password with?
How do you know it is Postgres related?

**Comment by fcturner** [comment]
Can you check the database table oc_passwords_share?

**Comment by abishai** [comment]
You can't insert NULL into id and be a friend of postgresql.
Autoincrements are implemented in pgsql in rather interesting manner - it's just DEFAULT value that querying sequence table for nextval(). So you can easily override this behavior by inserting your own values (like NULL) triggering constraint check.
Solutions:
1. removed id field from insert query entirely
2. use nextval('sequence_name_here')
https://www.postgresql.org/docs/9.5/static/functions-sequence.html

**Comment by fcturner** [comment]
Thanks, I'll see how I can fix this.

**Comment by fcturner** [comment]
Fixed in master: https://github.com/fcturner/passwords/commit/1a300f0e7ffda0ac3f71e072e07950a348e62e36

**Comment by fcturner** [comment]
Thanks!
