### ISSUE TITLE
Fatal error when resolving display name in PHP

### ISSUE THREAD

**Issue by roelio** [fcturner/passwords#259]
Hey,

I tried the latest code, but I get the following error:
![selection_015](https://cloud.githubusercontent.com/assets/900675/18544513/403b7882-7b35-11e6-9baa-c6b0c58850e5.png)

And in the log:
`
Exception: {"Exception":"Error","Message":"Call to a member function getDisplayName() on null","Code":0,"Trace":"#0 \/nextcloud\/apps\/passwords\/controller\/passwordcontroller.php(27): OCA\\Passwords\\Service\\PasswordService->findAll('_1126')\n#1 [internal function]: OCA\\Passwords\\Controller\\PasswordController->index()\n#2 \/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(160): call_user_func_array(Array, Array)\n#3 \/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(90): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Passwords\\Controller\\PasswordController), 'index')\n#4 \/nextcloud\/lib\/private\/AppFramework\/App.php(111): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Passwords\\Controller\\PasswordController), 'index')\n#5 \/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('OCA\\\\Passwords\\\\C...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#7 \/nextcloud\/lib\/private\/Route\/Router.php(293): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#8 \/nextcloud\/lib\/base.php(967): OC\\Route\\Router->match('\/apps\/passwords...')\n#9 \/nextcloud\/index.php(48): OC::handleRequest()\n#10 {main}","File":"\/nextcloud\/apps\/passwords\/service\/passwordservice.php","Line":64}
`

**Comment by fcturner** [comment]
I take it you use LDAP? Or both LDAP and database?

**Comment by fcturner** [comment]
Please download the latest master ([:package:zip](../archive/master.zip) or [:package:tarball](../archive/master.tar.gz)). It should be fixed now.

**Comment by fcturner** [comment]
(and please reopen this issue when it isn't :smile:)

**Comment by roelio** [comment]
@fcturner still exception about the display name:
`Exception: {"Exception":"Error","Message":"Call to a member function getDisplayName() on null","Code":0,"Trace":"#0 \/nextcloud\/apps\/passwords\/controller\/passwordcontroller.php(27): OCA\\Passwords\\Service\\PasswordService->findAll('_1126')\n#1 [internal function]: OCA\\Passwords\\Controller\\PasswordController->index()\n#2 \/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(160): call_user_func_array(Array, Array)\n#3 \/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(90): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Passwords\\Controller\\PasswordController), 'index')\n#4 \/nextcloud\/lib\/private\/AppFramework\/App.php(111): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Passwords\\Controller\\PasswordController), 'index')\n#5 \/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('OCA\\\\Passwords\\\\C...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#7 \/nextcloud\/lib\/private\/Route\/Router.php(293): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#8 \/nextcloud\/lib\/base.php(967): OC\\Route\\Router->match('\/apps\/passwords...')\n#9 \/nextcloud\/index.php(48): OC::handleRequest()\n#10 {main}","File":"\/nextcloud\/apps\/passwords\/service\/passwordservice.php","Line":65}`

It works when I comment out line 65. Looks like the exception is not caught...

**Comment by roelio** [comment]
The call `\OC::$server->getUserManager()->get($uuid)` doesn't seem to return a user. I checked the uuid and that seems to be okay.

**Comment by fcturner** [comment]
Please try again. I'm now checking for valid GUID, which your username isn't. So it work fine now.

**Comment by roelio** [comment]
That gives me another (unrelated) error:
`Exception: {"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve OCA\\Passwords\\Controller\\PasswordController! Class OCA\\Passwords\\Service\\PasswordService does not exist","Code":0,"Trace":"#0 \/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php(105): OC\\AppFramework\\Utility\\SimpleContainer->resolve('OCA\\\\Passwords\\\\C...')\n#1 \/nextcloud\/lib\/private\/AppFramework\/App.php(98): OC\\AppFramework\\Utility\\SimpleContainer->query('OCA\\\\Passwords\\\\C...')\n#2 \/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('OCA\\\\Passwords\\\\C...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#3 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#4 \/nextcloud\/lib\/private\/Route\/Router.php(293): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#5 \/nextcloud\/lib\/base.php(967): OC\\Route\\Router->match('\/apps\/passwords...')\n#6 \/nextcloud\/index.php(48): OC::handleRequest()\n#7 {main}","File":"\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","Line":90}
`
Maybe a nextcloud vs owncloud thing?

**Comment by fcturner** [comment]
What the *! Please wait, I'll look into still now.

**Comment by fcturner** [comment]
Right, I forgot two brackets. Please try again :smile:

**Comment by roelio** [comment]
It's not giving errors anymore but I think the code used to retrieve a user display name is not working.
I made some configuration changes so that the owncloud_name column in the ldap mapping contains the the uuid that is supplied by the LDAP. 

When I try to use `\OC::$server->getUserManager()->get('39469109-768611e6-8549b7ba-27395478')` it returns null. 

Also the uuids do not fit the regex you just created.

**Comment by roelio** [comment]
I would love to help, but I have a hard time finding the docs about the user manager.

**Comment by fcturner** [comment]
> but I have a hard time finding the docs about the user manager

Exactly! Awful support for developers :cry: 

I thought UUID are real GUIDs, so they should contain:
- 8 characters (both letters and numbers)
- 4 characters
- 4 characters
- 4 characters
- 12 characters
Each set of characters being separated by a `-`. Your ID `39469109-768611e6-8549b7ba-27395478` doesn't come even close to a GUID... But the error you had was because of a username `_1126`, according to your log.
So I don't want the `\OC::$server->getUserManager()` to check for  `_1126`, but when using LDAP, it does need to check for GUID's. This function *did* work for other LDAP users, as they can now share with other LDAP users, using a share dialog with valid display names, coming from this function: #175.

How was your UID `39469109-768611e6-8549b7ba-27395478` created?

**Comment by fcturner** [comment]
> I made some configuration changes so that the owncloud_name column in the ldap mapping contains the the uuid that is supplied by the LDAP.

I don't know if I can support this. It would be impossible to think of every possibility an admin has to alter their configuration.

**Comment by fcturner** [comment]
I'll release v19 now, and postpone this to 19.1 (which could be released very soon, nevertheless).

**Comment by roelio** [comment]
After some research it looks like the owncloud ldap backend is getting the wrong uuid.
I'm using a IPA ldap backend and it supplies both nsuniqueid and ipauniqueid. The [ldap backend code](https://github.com/owncloud/core/blob/ca595611f5d9c81a7c6437f4e013bb0ed01a0376/apps/user_ldap/lib/access.php#L1068) can autodetect the ldap user id. In my case it will always choose the nsuniqueid because it comes before the ipa one. When I override the uuid attribute it works like a charm.

Thanks for your quick response and great work!

**Comment by roelio** [comment]
Yeah probably or make it a bit more robust by uppercasing the uuid that you test against the regex. That failed for me because my uuid has lower case.

Thanks again.

**Comment by fcturner** [comment]
:+1:

**Comment by fcturner** [comment]
> When I override the uuid attribute it works like a charm.

How did you do this?

**Comment by fcturner** [comment]
Another user has the same problem...

**Comment by roelio** [comment]
The problem with upgrading #265 I also encountered, but because we do not use it in production yet I just started with a clean slate.

**Comment by fcturner** [comment]
So how did you overwrite the uuid attribute?

**Comment by roelio** [comment]
In the ldap admin of nextcloud on the expert tab I do:
![selection_017](https://cloud.githubusercontent.com/assets/900675/18787240/3fb5d56a-81a2-11e6-8dc8-74927fd47a5b.png)
