### ISSUE TITLE
Password sharing not working

### ISSUE THREAD

**Issue by roelio** [fcturner/passwords#261]
Hey again :-)

I tried to share a password but it doesnt seem to work. The one that the password is being shared with cannot see it in its list.
In the oc_passwords_share there is a record. The column sharedto contains the username, but shouldnt it be the uuid?

**Comment by fcturner** [comment]
I think this is being caused by your altered configuration like you said in #259. 
It actually works well on regular LDAP services and OpenLDAP. I would really like to help, but don't know how...

**Comment by roelio** [comment]
Currently the only difference with the default config is that I specify the specific uuid that the ldap backend should use.

Also it was working before the updates from this week. I will investigate it a bit myself and will come back to you.

ps. Have you tested it with a LDAP backend?

**Comment by roelio** [comment]
Found my problem:

When i change the value of the input box to the displayname (this is the uuid for ldap users) instead of the uid (which is actually the displayname for ldap users) it works! Check https://github.com/fcturner/passwords/blob/master/js/script.js#L1541

**Comment by fcturner** [comment]
But this is exactly the other way around with other LDAP users! How can this be?

**Comment by roelio** [comment]
I don't think my configuration is that weird. If you know for sure that other ldap users don't have the problem then I'm puzzled too...

**Comment by fcturner** [comment]
@roru69, @schannall 

@roelio says:
> Found my problem:

> When i change the value of the input box to the displayname (this is the uuid for ldap users) instead of the uid (which is actually the displayname for ldap users) it works! Check https://github.com/fcturner/passwords/blob/master/js/script.js#L1541

Do you run into this same trouble with LDAP, this being the solution?

**Comment by schannall** [comment]
I wanted to try but somehow my passwords are not beeing decrypted now. Reinstalling passwords did not help at first. I'll try some and report back.

sC

**Comment by fcturner** [comment]
ownCloud log something odd? When shared passwords are not decrypted, it show a button with 'Invalid share key'.

**Comment by schannall** [comment]
Okay got Passwords working again.
Changing line 1541 to
`$('#ShareUsers').append('<label><input type="checkbox" value=' + displayname + '><div class="share_avatar avatar_' + uid_escaped + '"></div><span>' + uid + '</span></label><br>');`
fixes sharing for me. Thanks for your hard work!

sC

**Comment by fcturner** [comment]
Implemented in master.

A really big thanks to you guys! No development without contributors :+1:
