### ISSUE TITLE
When using user_saml the password auth doesn't work

### ISSUE THREAD

**Issue by roelio** [fcturner/passwords#263]
After configuring user_saml I cannot use the nextcloud extra authentication for the password app. 

To circumvent this problem maybe there could be a administrator option to force the users not to use the nextcloud extra authentication.

**Comment by fcturner** [comment]
Good idea!

**Comment by fcturner** [comment]
Does it work when you set a master password?
I'm curious if this only happens when you set Passwords to authenticate with the ownCloud/NextCloud password.

**Comment by roelio** [comment]
@fcturner The master password option does work

**Comment by fcturner** [comment]
Great, then I will block the extra ownCloud/NextCloud authentication when user_saml is activated and let the admin know.

**Comment by fcturner** [comment]
Please try the `user_saml` branch :smile: 

I can't check it myself, since I don't use user_saml.

**Comment by roelio** [comment]
Works like a charm :+1: 

The master password still works, but the option is not displayed in drop down with the new code. 
Maybe I can look into why the nextcloud auth doesn't work when I find some time.

Thanks for the fix!

**Comment by fcturner** [comment]
That's odd... thanks for helping!

**Comment by fcturner** [comment]
Figured it out: https://github.com/fcturner/passwords/pull/267/commits/9f507c8cdaab0d336064fde56b3c7416075abf5b
