### ISSUE TITLE
Change git commands to always download latest stable version

### ISSUE THREAD

**Issue by e-alfred** [fcturner/passwords#266]
Hello,

currently the git commands always download the latest release instead of the last stable one. I think for most end users it would be better to add the tags of the last stable version to the commands like for example:

`git clone --branch 19 https://github.com/fcturner/passwords.git  /var/www/owncloud/apps/passwords`

**Comment by fcturner** [comment]
Thanks! I edited the readme and changed it on apps.owncloud.com too.
