### ISSUE TITLE
LDAP Password share issue and filter option not working

### ISSUE THREAD

**Issue by Takalele** [fcturner/passwords#268]
Hi,

the password sharing function between ldap users is not working if there are users with 
similar names/cn.
If i share a password with Michael Co then the other Michael is automatically selected (shown in the editing window) and Michael Co is not able to see the shared password, if i share with another user it works fine.

![share1](https://cloud.githubusercontent.com/assets/22237036/18733884/1868fcc8-806f-11e6-9b13-fefa5076a744.png)
![share2](https://cloud.githubusercontent.com/assets/22237036/18733888/1c1f6744-806f-11e6-8f98-f6b6448a1498.png)
![sharemichaelco](https://cloud.githubusercontent.com/assets/22237036/18734236/b20d24f0-8072-11e6-8fd9-31316e1ccf86.png)

Minor Issues

The filter function is not working with 50+ passwords

the username is not hidden with a shared password
![shareusernamenothidden](https://cloud.githubusercontent.com/assets/22237036/18734167/de9637ec-8071-11e6-98a8-10aa6c0d4284.png)

I am using ownCloud 9.2.0 pre alpha (beta) with passwords v20-beta2 and this ldap patch https://github.com/owncloud/core/pull/25601/commits/793b6383db3d91f1befb90d16f5922540b6750fe

any idea?

anyway cool app and awesome work keep it up! thank you.

regards,
Takalele

**Comment by fcturner** [comment]
> If i share a password with Michael Co then the other Michael is automatically selected (shown in the editing window) and Michael Co is not able to see the shared password, if i share with another user it works fine.

Please try again with v20-beta3 ([:package:zip](../archive/master.zip) or [:package:tarball](../archive/master.tar.gz)).

> The filter function is not working with 50+ passwords

This is definitely fixed in 20-beta3, thanks for catching that!!

> the username is not hidden with a shared password

This is according to your own settings. A username will be hidden if you set that option on you personal page.

**Comment by Takalele** [comment]
great! now it works wonderful, thank you!

regards,
Takalele

**Comment by fcturner** [comment]
👍
