### ISSUE TITLE
ssl-proxy isn't recognize

### ISSUE THREAD

**Issue by lo-man** [fcturner/passwords#27]
I use a webhoster with a ssl-proxy. In my owncloud config is 'forcessl' => true, enabled and it works as it should. My adress is always https://ssl-proxy.com/mycloud_adress.com. But the app passwords shows me a warning message that I don't use a secure connection.

**Comment by fcturner** [comment]
This needed a quick fix: https://github.com/fcturner/passwords/commit/e0ca88e343fe8d500517205f1a05ec23226cc60e

If you download the master, it should be good!
