### ISSUE TITLE
LDAP Users stuck at "Decrypting Passwords..."

### ISSUE THREAD

**Issue by mikshepard** [fcturner/passwords#279]
After LDAP support was added to this app, all LDAP users are stuck at the "Decrypting Passwords..." screen.  Non-LDAP users work fine.  Syncing with the latest git master (version 20-beta5) gives the same results.  I've wiped the mysql tables and regenerated them, but no difference there either.  Running on Ubuntu 14.04, ownCloud 9.0.4, mysql 5.5.52.  There is a report of this on ownCloud 9.2 as well.

Here is the debug output:   [http://pastebin.com/uG1UYd1a](url)

**Comment by fcturner** [comment]
Thanks. Too bad this is still happening. The info you sent is all level 0 (debug). No errors whatsoever. Are there any errors in your ownCloud log as well? 

Can you comment ('disable') the lines in service/passwordservice.php that use the getDisplayName function and see if it works then? I can create a separate branch to facilitate you.

**Comment by mikshepard** [comment]
Thank you for the quick response.  There are no errors at all in log when run at the normal log level of 2.

As per your suggestion, I commented out lines #70, #182, and #191.  Now I get an message stating "Error: Could not load passwords".  

This was in the log (Log Level 2):  {"reqId":"XXXXXXXXXXXXXXXXXXXX","remoteAddr":"X.X.X.X","app":"PHP","message":"syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at \/var\/www\/owncloud9\/apps\/passwords\/service\/passwordservice.php#75","level":3,"time":"2016-10-05T11:41:29-05:00","method":"GET","url":"\/index.php\/apps\/passwords\/passwords","user":"mikshepard"}

**Comment by fcturner** [comment]
Now that's wrong... Wait a sec.

**Comment by fcturner** [comment]
Please try my [mikshepard branch](https://github.com/fcturner/passwords/tree/mikshepard) 😉

**Comment by mikshepard** [comment]
Thank you for creating the new test branch.  I did try it out and have the same results, stuck at "Decrypting passwords...".   Nothing in the log file either.

**Comment by fcturner** [comment]
Ah! Haven't you enabled the Activity app??

**Comment by fcturner** [comment]
Please try again :smile:

**Comment by mikshepard** [comment]
Thanks for the update and for working on this.  I'm still getting stuck at "Decrypting passwords..." though.  The logs are showing a different Activity error now:  ""Class 'OCA\\Passwords\\Activity' not found at \/var\/www\/owncloud9\/apps\/passwords\/service\/passwordservice.php#391"

**Comment by Pyhrra** [comment]
Good Day! Ive recently  updated to V19 and all my ldap users are also stuck with "Decrypting Passwords"

**Comment by fcturner** [comment]
@Pyhrra Would you like to test my [mikshepard branch](https://github.com/fcturner/passwords/tree/mikshepard)? Let me know if the log returns errors about the activity app, (like mikshepard).

**Comment by Pyhrra** [comment]
@fcturner Seems to have worked when i loaded everything. I will let you know if any other errors arise. Will this issue be fixed in the final release of V20 ?

**Comment by fcturner** [comment]
I did, the master already contains the fix. Thanks for testing! The activity error must be solved in another issue.
