### ISSUE TITLE
v20 upgrade issues

### ISSUE THREAD

**Issue by intirix** [fcturner/passwords#292]
It appears that the REST API has changed slightly.  The "deleted" field appears to have changed from being the string "0"/"1" to being an actual boolean of true/false.  Is this expected?  Also, when I upgraded my QA environment, some of the passwords are not showing up correctly in the REST API.  The UI shows them just fine.  The pass and properties fields just show up as what appear to be hex values.  Not all the passwords have this issue.

    {   
        "address": "",
        "creation_date": "1970-01-01",
        "deleted": false,
        "id": 2,
        "loginname": "",
        "notes": "",
        "pass": "2d4608e06c45bb4a5a0de4df1f3ac2b6af06663a71fad09522ed6f483886d36d7ac7bfd2bb141383807151e396358598c8255130430b113878ca6c271f1f8ea59790b683540a9c74e452fe9768ddf4d2b0d9316fa3af70f8aec5dd4625436196bd583c48cd261518de14f060d6acfe3c31a03865b90409882f9135e24b265dd788d3c4db9edb25e6e8f5dbedbdc5a9ba778771b7c143d6083a2e9d559a90717fbba983f2007758665068d62aeacb4527c421c08c424d173f9ed6bada934af6ea087743411340845a",
        "properties": "1e937d6cbd052e0b256ae31d1bb6793659e73488cf51d4d44fe85ebeb1ab523f696a28005e8db6dec74ffd5d8403fa5ce25a00eb36064690706a66351f0d7bd5eba67bc5552bb1beac75fc835aee85b67162d2b7192ece7fa618120ec84b080d930247d031eb57630f5b19811455517730659ca8446a89cec1032a845312946382dab56a9d5d4c9453cdffce18280b19f3d2811fcf3b1063f2dc77e16408e5c1a2c0cd400cffbf1c8c5c88b8030656a0081443b89e75254130bdff655e8d8d6f0695b5f9ae58c477270f0bc1d2da05c4c7279501e76ccf848360a21d2f2c6fce8c66004e55ee0686f8c488a50f829045351d327b415014a753e3e99a51f5a7c0a6df73f9286056c68fbdd408702a69d95925464c61a0744902ee77f11ecb7d884d9082ca6a0e32ae5705db473a83fc1d4a23ead32f4e3aa3a53647733fea2a266a1afc5899025cf8163ca488db23904fa9f61e70704d189cd640173fe90c1361d5fa6ebd4cb82391765c2f6c539818caa3bfcb942d2077ca0e1520a826887a458a99e318440bae3490157d0ae821c32a992dc23b2bcb6643",
        "user_id": "pwuser1",
        "website": "hgfhgf"
    },

**Comment by fcturner** [comment]
Yes, that's correct. I had to change the deleted flag to real booleans, because Firefox combined with PostGreSQL didn't like it otherwise. So, the deleted flag is indeed now a Boolean. I update CHANGELOG.md with every edit, but I should have updated you personally too. I'm sorry for that. I do think this was already implemented in v19 rather than v20. 

I had to change the columns password and properties to string format. So that's what you see here; encrypted hashes of the real values. In other words, those values haven't been decrypted at all. I don't know why. Are they shared passwords?

**Comment by fcturner** [comment]
I'm thinking about removing the deprecated columns by the way: address, login name, creation date, notes. 

Everything but id, website, pass, properties and deleted.

**Comment by fcturner** [comment]
And user_id of course :wink:

**Comment by intirix** [comment]
Removing those other fields shouldn't impact me, but I will write up some unit tests just to be sure.  Also, the 2 passwords that stopped working are not shared.  I only tried the latest beta because one of my users tried it and got a JSON parse error.  I don't know the circumstances in that situation.  I have the ability to roll back my QA environment back to v19.  I might try the upgrade again.  I didn't notice a change in v19.  Also, when I tried to upgrade your app, the Owncloud upgraded itself to 9.0.4 for some reason.

I see a warning in the logs, but I honestly can't say if this is noise or an actual issue:

{"reqId":"bzAs1gfkyB9Rs+RD7fil","remoteAddr":"172.17.0.1","app":"PHP","message":"Undefined offset: 9 at \/var\/www\/html\/ocdev\/apps\/passwords\/service\/passwordservice.php#37","level":3,"time":"2016-11-20T17:55:21+00:00","method":"GET","url":"\/ocdev\/index.php\/apps\/passwords\/api\/0.1\/passwords","user":"pwuser1"}

**Comment by fcturner** [comment]
Thanks, I'll see if I can relate anything to that log line.

**Comment by fcturner** [comment]
I this solved?

**Comment by intirix** [comment]
Sorry, I haven't followed up on the decryption issue.  Consider it closed for now
