### ISSUE TITLE
New special characters....

### ISSUE THREAD

**Issue by IzK666** [fcturner/passwords#300]
When a password contains some specific characters, it can't be read again and (not always) throws an error every time you reload website.

The string is:
&#_
where _ can be numbers or an x followed by numbers.

**Comment by IzK666** [comment]
I have created a [small patch](https://github.com/IzK666/passwords/tree/HTML-encoding) to avoid the creation of those passwords.

But can't figure out how to save it.

**Comment by mmassing** [comment]
This is probably related to #311 and should be fixed by #312

**Comment by fcturner** [comment]
Fixed in #312
