### ISSUE TITLE
Allow reset of master password

### ISSUE THREAD

**Issue by Luticus** [fcturner/passwords#307]
If a user forgets their master password what is the proper method for an admin to reset their password db so that they can rebuild it.  (obviously I know that recovering the passwords would probably be impossible).  I just want to set it so that the user can just "start over".

**Comment by fcturner** [comment]
Your best shot is to edit the `oc_preferences` table and look at the settings for your user:
```SQL
SELECT 
	*
FROM
	oc_preferences 
WHERE 
	appid = 'passwords' 
	AND configkey IN ('extra_auth_type', 'master_password');
```
Then set the `extra_auth_type` to `owncloud` and the `master_password` to `0`.
After this, the user can log in the Passwords app with the ownCloud/NextCloud-password and change the setting within the app back to use a master password.

**Comment by Luticus** [comment]
Awesome, thanks.  In future versions you should consider a way to change/unbrick user accounts to the app from the admin panel.  I can work with sql but I think many oc/nc admins would be quite stuck or risk damaging their databases with bad sql statements that affect more records than they intend..

**Comment by fcturner** [comment]
Very good point, just thought of it. I'll make it an enhancement then :+1:

**Comment by fcturner** [comment]
This is implemented in the latest master.

#### Package download
(remember to rename the folder to `passwords`)
[:package:ZIP file](../archive/master.zip)
[:package:TAR file](../archive/master.tar.gz)

#### Command line 
(assuming `/var/www/owncloud/` as your root location)
 ```sh
rm -rf /var/www/owncloud/apps/passwords
git clone https://github.com/fcturner/passwords.git /var/www/owncloud/apps/passwords
```
