### ISSUE TITLE
Install on nextcloud10 failed

### ISSUE THREAD

**Issue by rasos** [fcturner/passwords#310]
I have cloned according to instructions with git branch 19 into passwords folder.
When enabling the app as admin, I get:
`Archives of type text/html are not supported`
The passwords app is not getting enabled.
I also tried with occ upgrade, no luck. Is there anything I have overseen?

```
/var/www/nextcloud/apps $ ls -al passwords
insgesamt 92
drwxr-xr-x 12 www-data www-data  4096 Jän 28 23:16 .
drwxr-xr-x 39 www-data www-data  4096 Jän 28 23:18 ..
drwxr-xr-x  2 www-data www-data  4096 Jän 28 23:16 appinfo
-rw-r--r--  1 www-data www-data    63 Jän 28 23:16 AUTHORS.md
-rw-r--r--  1 www-data www-data 19492 Jän 28 23:16 CHANGELOG.md
drwxr-xr-x  2 www-data www-data  4096 Jän 28 23:16 controller
drwxr-xr-x  2 www-data www-data  4096 Jän 28 23:16 css
drwxr-xr-x  2 www-data www-data  4096 Jän 28 23:16 db
drwxr-xr-x  8 www-data www-data  4096 Jän 28 23:16 .git
drwxr-xr-x  2 www-data www-data  4096 Jän 28 23:16 img
drwxr-xr-x  2 www-data www-data  4096 Jän 28 23:16 js
drwxr-xr-x  3 www-data www-data  4096 Jän 28 23:16 l10n
-rw-r--r--  1 www-data www-data 17814 Jän 28 23:16 README.md
drwxr-xr-x  2 www-data www-data  4096 Jän 28 23:16 service
drwxr-xr-x  2 www-data www-data  4096 Jän 28 23:16 templates
```

**Comment by fcturner** [comment]
Not that I know of 😞 
I've never heard others about this bug in NC10. I know that ownCloud gives this error when you try to download it via the App Store, which I don't support. But with Git, everything should work perfectly.

Have you tried to alter the permissions?

**Comment by fcturner** [comment]
Where you in the App Store when you clicked `Enable`? You should on the 'Inactivated apps' page. Still having this error then?

**Comment by fcturner** [comment]
Please check #323. NextCloud is no longer supported. You could use the fork mentioned there.
