### ISSUE TITLE
Getting 'static' error when adding password

### ISSUE THREAD

**Issue by Andrew908** [fcturner/passwords#32]
When I add a password in the password manage I get the following error: Non-static method OCA\Passwords\Service\Encryption::makeKey() should not be called statically, assuming $this from incompatible context at /usr/share/nginx/html/owncloud/apps/passwords/service/passwordservice.php#34 
Could you please tell me where this problem comes from ?

**Comment by fcturner** [comment]
Yes, this was initially pulled in #25. Seems a strange error. Will look into this. Thanks.

**Comment by fcturner** [comment]
Fixed with the 8.0.6 release (https://github.com/fcturner/passwords/commit/aa76297a04e9f3d18bf5ff189aa8bbc531e7a174)
