### ISSUE TITLE
Does not work under Nextcloud 12

### ISSUE THREAD

**Issue by seraphyn** [fcturner/passwords#322]
Updated to the last Version.
Asks for password, gave an empty box with only an Ok-button and do not shown any passwords after it.

**Comment by HanFox** [comment]
I get 2 boxes. One that states "Error: Could not load categories" and the other "Error: Could not load passwords".

**Comment by seraphyn** [comment]
Does not work....
Now I get the two Errors you've mentioned.
I used git clone to get the new version. Which one does you use?

**Comment by HanFox** [comment]
I git clone the master:
`git clone https://github.com/fcturner/passwords.git /var/www/owncloud/apps/passwords`

**Comment by dacendo** [comment]
Thanks for the fix, it worked for me.

**Comment by weipah** [comment]
Had the same issue after update to NC12, but the fix from @HanFox worked for me.
Thanks!

**Comment by seraphyn** [comment]
Did the same.
Try it once more

**Comment by seraphyn** [comment]
Changed my imported data to passman.
Hope there will be a bugfix soon.
Greetings

**Comment by HanFox** [comment]
@seraphyn You shouldn't close this. It's not fixed yet.

**Comment by weipah** [comment]
@seraphyn you need to change both lines in both mentioned files and reload the passwords site. hth

**Comment by seraphyn** [comment]
@weipah i know how to code 😉
Look at the issues Made by me in this App and other ones.
But it is important for me that it will work atm, so I changed to another App atm and will find Out the reason why in my holidays.

**Comment by seraphyn** [comment]
@HanFox  reopened for you

**Comment by HanFox** [comment]
So after doing the recommended DB update to utf8mb4 this broke again (maybe this was why you still had issues @seraphyn ?).

Again, another easy fix for anyone else who takes the utf8mb4 dive without thinking (like me).

`db/categorymapper.php` line 21 change and `db/passwordmapper.php` line 91:
Change `utf8_general_ci` to `utf8mb4_general_ci`

**Comment by fcturner** [comment]
Thank you all! I will get back to this soon.

**Comment by fcturner** [comment]
Please refer to #323. OwnCloud related bugs will still be solved.

**Comment by HanFox** [comment]
Shame. I won't move to OC, but your manager is nicer than PassMan.

Well I understand the hobbyist thing, so no hard feelings ;)

**Comment by fcturner** [comment]
Thanks :wink:

**Comment by marius-wieschollek** [comment]
Just in case you care, I had a little time yesterday so i made a Port for Nextcloud 12 here: https://github.com/marius-wieschollek/passwords . I fixed every problem I encountered and added a mobile style. If you want to you can test it out.

**Comment by HanFox** [comment]
@marius-wieschollek: Looks good. I'll check it out.

I'd argue you've made it 99% less secure by using spaces instead of tabs though :-1:

**Comment by marius-wieschollek** [comment]
@HanFox I am deeply saddened by this serious mistake.
