### ISSUE TITLE
Exporting passwords from nextcloud 12

### ISSUE THREAD

**Issue by studunihd** [fcturner/passwords#325]
Regretably, I did not check the compatability of passwords with NC12 before upgrading and cannot access my passwords through Nextcloud anymore.

Is there a way to export/decrypt the passwords directly from the database?

**Comment by duh-nm** [comment]
The easiest way would be to remove the passwords folder, and replace it with the NC fork https://github.com/marius-wieschollek/passwords , which will open fine, and allow you to export if you still choose to. You will not be able to directly export from the database due to the encryption.

**Comment by hobas** [comment]
Did you take a look at this closed issue? 
https://github.com/fcturner/passwords/issues/322

**Comment by studunihd** [comment]
Thank you both! It works again after moving to the fork.
