### ISSUE TITLE
Tool to migrate from Passwords to Passman ?

### ISSUE THREAD

**Issue by Gardakant** [fcturner/passwords#326]
Hi, just upgraded to NC12 and saw you don't support NC anymore.
I can't understand that without problem, it's totally legit. But is there a way to recover my passwords without installing a VM and an older Nextcloud version ?
Thx

**Comment by HanFox** [comment]
You can just use this fork for NC12: https://github.com/marius-wieschollek/passwords

**Comment by Gardakant** [comment]
Had no luck, it says it can't load passwords and categories. Just like with origjnal app since migrating to NC 12.

**Comment by Gardakant** [comment]
ok, finally worked after downloading the latest master branch, thanks !!

**Comment by Gardakant** [comment]
just closing this issue

**Comment by pafcioooo** [comment]
@fcturner, maybe in #323 you could put info about this fork https://github.com/marius-wieschollek/passwords that @HanFox have mentioned :-)
