### ISSUE TITLE
"This app is not nearly as secure as Passwords"

### ISSUE THREAD

**Issue by brantje** [fcturner/passwords#327]
Hi there,
one of the Passman authors here.. I’ve noticed your statement so I have started digging in your app.

**First things first**:
You can clearly see that passwords app is sending the credentials in plain text, so if someone is using HTTP, all their passwords will be exposed.
![image](https://user-images.githubusercontent.com/2758767/28996006-a03558fe-79f7-11e7-8ec1-0f0ba130859b.png)
According to this, your statement of "passwords is using client-side encryption" is incorrect, wrong, and misleading. If you were using client side encryption it would look like below, like on passman.

Passman on the other end sends the credentials encrypted:
![image](https://user-images.githubusercontent.com/2758767/28995707-b4711e72-79f0-11e7-82a6-60098de08164.png)

**Second one**:
Your encryption class uses `mcrypt_` functions which are deprecated in PHP 7.1.
As far I can see, you can copy our server side encryption class that is using the openssl lib.

**Third one**:
Auth password (and thus encryption password), are send in plain text over the internet to server.
![image](https://user-images.githubusercontent.com/2758767/28995808-40e460ba-79f3-11e7-945f-d0b447dd8dd5.png)

**Forth one**:
XSS. Your app is vulnerable for [XSS](https://en.wikipedia.org/wiki/Cross-site_scripting):
![image](https://user-images.githubusercontent.com/2758767/28996171-016436d8-79fb-11e7-9f1d-af2a8efe9f74.png)

Results in:
![image](https://user-images.githubusercontent.com/2758767/28996179-22d637a8-79fb-11e7-8073-1abb2759ed0c.png)

Also at categories you have an XSS vulnerability
Same as CSV import

So to sum this all up, to me it seems passman is more secure than passwords app, and therefore the statement "Passman app is not nearly as secure as Passwords ." seems invalid to me.   

I ask you therefore to add client side encryption or remove said statement, it’s misleading users to believe you encrypt passwords before sending them to the server (at the client side, not at the server side).

In the future, we would appreciate if you raised an issue, or contact us directly about our encryption before using words like "abysmal" without justification.

I would like to know what do you mean by "abysmal" and what does it have to do with our encryption lib (server or client side) and it's security implications.

**Comment by fcturner** [comment]
Nice, thanks for bashing. Really gets the fire on the oil war between OC and NC. Pathetic.

> so if someone is using HTTP, all their passwords will be exposed.

Blocked by default, look into the settings, moron.

 > Your encryption class uses mcrypt_ functions which are deprecated in PHP 7.1.

This issue is being addressed already in #134. Long wanted enhancement, and with the NC fork of my app, I hope this will be implemented soon.

> Auth password (and thus encryption password), are send in plain text over the internet to server.

Latest version uses POST. Maybe you should look better.

> So to sum this all up, to me it seems passman is more secure than passwords app

I disagree. And you prove that NC-ers tend you communicate in a rude and despicable way.
