### ISSUE TITLE
Editing values doesn't work in Firefox

### ISSUE THREAD

**Issue by IzK666** [fcturner/passwords#50]
Hi!
I'm back. I was away for a week for holidays :yum: 

It's amazing. It seems a new app! So many changes...

About the new version:
View and edit doesn't work on Firefox 36, 38 or 39. On Opera 12 works like a charm.... Thank you! :stuck_out_tongue: 

Although it's a bit annoying when the text appear because sometimes passwords are long and the columns need to resize.

About duckduckgo icons there is a mistake. I write an example (for ebay).
You request this address: https://icons.duckduckgo.com/ip2/ebay.ico
The url should be: https://icons.duckduckgo.com/ip2/ebay.es.ico (I use the spanish url)

PS: On Vivaldi Browser works too. (Chromium based)

**Comment by fcturner** [comment]
Hey, welcome back! Thanks for the great compliments!

So this Firefox issue is present in 8.0.8? Or 8.0.7 and lower only?


The DDG-URL should work; it uses the field entry for `website`, so shouldn't be a problem if you've entered `ebay.es` as your website.

**Comment by fcturner** [comment]
Ho, I mentioned hovering leads to column resizing, so you obviously have 8.0.8. 

This can be fixed by simply edit the overflow in CSS. I will push an update for this. 

I will need to look into Firefox...

**Comment by lo-man** [comment]
can confirm this behaviour. In Waterfox 39 it doesn't work but in Vivaldi an IE11 it works. I've no script blocker active. Checked this with a new fresh Waterfox profile without any addons.

**Comment by fcturner** [comment]
Fixed as of release 8.0.9.
