### ISSUE TITLE
Addons/plugins for top-3 no nonsense browsers (Firefox, Chrome and Safari)

### ISSUE THREAD

**Issue by AisoPlee** [fcturner/passwords#55]
I think there really should be the idea in the "far far away section" that at one point there should be some sort of "Firefox Addin", so this could replace the Firefox built in Password Keeper, that probalby 99% of all (Firefox) useres use. it should also automatically Fill in Forms. Because any other sollution means: allways CopyPase username/password (and therefore: allways keep the passwords Page open....)

Of course ther should also be an Addind for Chrome, Edge, Opera and any other Browser you could think of :smile:

**Comment by fcturner** [comment]
Great idea! I will set the proper label for this one :smile:

**Comment by eglia** [comment]
I started working on a firefox add-on: [GitHub](https://github.com/eglia/ff-oc-passwords) / [Mozilla](https://addons.mozilla.org/en-US/firefox/addon/firefox-owncloud-passwords/)

This is the first time I'm developing a firefox add-on (or anything in javascript for that matter) and I'm doing it mainly for my own needs, so please forgive me if it is a little rough :smile:

**Comment by fcturner** [comment]
Great!!!!!! Thanks!

**Comment by thefirstofthe300** [comment]
So I have started work on [my own Chrome extension](https://github.com/thefirstofthe300/ownCloud-Password).  Anyone who has extension development experience is welcome to help me (I have no experience so please bear with me).

**Comment by fcturner** [comment]
Firefox: https://addons.mozilla.org/en-US/firefox/addon/firefox-owncloud-passwords/
Chrome: https://github.com/thefirstofthe300/ownCloud-Password
Thanks to eglia and thefirstofthe300!

API now ready.
