### ISSUE TITLE
Install from appstore withn OC not working

### ISSUE THREAD

**Issue by UnnamedHero** [fcturner/passwords#56]
Can't install app from appstore within OC.
It shows enabled, no app icon appears. After refreshing page app becomes disabled. After pressing "enable" button OC says "App Folder already exists". App folder exits in filesystem, but it is empty.

OC: 8.1.1
OS: CentOS 7.1.1XXX
Db: postgresql

Other apps install fine!

**Comment by fcturner** [comment]
Strange, I cannot reproduce this. It just downloads and installs fine.
I tested the link, and it leads to the Passwords master correctly. What does your ownCloud log say? 

This might not be related to my app, albeit other apps are installing fine...

**Comment by UnnamedHero** [comment]
OC log says only 

```
"app":"core","message":"\u041a\u0430\u0442\u0430\u043b\u043e\u0
433 \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u044f \u0443\u0436\u0435 \u0441\u0443\u0449\u0435\u0441\u0442\u043
2\u0443\u0435\u0442","level":3,"time":"2015-08-17T19:51:01+03:00","method":"POST","url":"\/index.php\/settings\/ajax\/enablea
pp.php"}
```

What can I do to provide more useful logs?

**Comment by fcturner** [comment]
Maybe switch `appcodechecker` off?

I'm very sorry, I don't know how else I can help you. I can't reproduce this, really.

**Comment by fcturner** [comment]
Are you on Linux?
Then the good old 
`wget https://github.com/fcturner/passwords/master.zip`

`unzip master.zip`

`mv passwords-master /var/www/html/owncloud/apps/passwords`

should do the trick...

**Comment by UnnamedHero** [comment]
Yes, I'm using Linux. Of course I can download and install it manually, but it is boring :)
I'm really want to discover root of the problem. Will try to get more debug logs with OC console.May be something wrong with OS.

**Comment by fcturner** [comment]
I agree :smile: 

I will await it then. I really like your thoroughness of willing to catch this thing! :+1:

**Comment by RealRancor** [comment]
Hi,

@fcturner You need to correctly release the App on apps.owncloud.com like described here:

https://github.com/owncloud/core/issues/18116#issuecomment-129445478

**Comment by fcturner** [comment]
Hi,

By 'You need' you actually mean ' Would you like', I guess :smile:

Thanks for the solution, but don't you think 
  1. "Draft a new release"
  1. Choosing 8.1.1
  1. Download 8.1.1 and ZIP it within a folder called "documents"
  1. Upload the resulting ZIP
  1. Publish the release 

... is a bit clumsy? Anyway, the step
`4. Upload the resulting ZIP` is not possible for me, since I only use GitHub online, with a computer where downloading software isn't an option and GitHub doesn't allow direct upload from a browser. 

In my point of view, you (ownCloud core team) really should fix the app store so that apps are downloaded correctly without this step. There must be a way.

Thanks anyway!

**Comment by RealRancor** [comment]
> GitHub doesn't allow direct upload from a browser.

GitHub allows the direct upload from a browser. ;-) So what you need to do to get this to work is:

1. Download https://github.com/fcturner/passwords/archive/8.0.11.zip
2. Re-package the archive so it contains a folder "passwords" and not "passwords-master" and call it "passwords.zip".
3. Edit the release 8.0.11 at https://github.com/fcturner/passwords/releases
4. Upload the new archive passwords.zip
5. Point https://apps.owncloud.com/content/show.php/Passwords?content=170480 to https://github.com/fcturner/passwords/releases/download/v8.0.11/passwords.zip

> you (ownCloud core team)

I'm not part of the ownCloud team. ;-)

But if you think there needs to be something fixed here you need to report this at https://github.com/owncloud/core/issues

**Comment by fcturner** [comment]
Thanks.

This means those users cannot use the git master! The whole GitHub idea about masters is useless with this system.

I am very sorry, but I will not let ownCloud do this for my app. I will state on the readme that installation from within ownCloud is not possible for this app, until ownCloud fixes this system.

**Comment by RealRancor** [comment]
> I am very sorry, but I will not let ownCloud do this for my app. I will state on the readme that installation from within ownCloud is not possible for this app, until ownCloud fixes this system.

You can give your feedback about this to the oC developers as already mentioned above.

**Comment by RealRancor** [comment]
@fcturner Thanks for deleting my comment. Thats the way it should be...

**Comment by fcturner** [comment]
You're welcome. 

You made your point already twice and I think you have a REALLY demanding tone in your communication. I feel like the primary ownCloud contributors can't seem to embrace app developers and that's really pity. 

Just leave it. I created this for the others.

**Comment by RealRancor** [comment]
This is not about my point but about giving you the info what requirements are currently needed so users are able to install and update your App via the appstore.

If you see a demanding tone in the infos/pointers how to correctly publish an app in the appstore (https://github.com/owncloud/core/issues/18116#issuecomment-129445478), the discussions about the reasons behind it (https://github.com/owncloud/core/pull/18190 from my deleted comment) and where to give feedback to the developers (https://github.com/fcturner/passwords/issues/56#issuecomment-136129630) then i don't know what you're reading between the lines.

But sure, this is your app. If you don't want to follow any advice you're more than free to do so.
