### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by IzK666** [fcturner/passwords#68]
TRANSLATIONS.js

<b> Missing:</b>
"Are you sure?"
"Block app when not connected to %s using a secured connection"
"Google DOES track your moves. Use DuckDuckGo preferably, since they don't"
"The \<b\>creation date\</b\> becomes <orange>orange after %s days</orange> and <red>red after %s days</red>."
"This will delete the password for"
"with user name"

<b>And those are useless (commented lines):</b>
"from"
"Please enter the username of the user you want to share this password with:"

**Comment by fcturner** [comment]
Thanks!

'Useless' is for future share function.

**Comment by Nemofly** [comment]
There are still translations missing:
Active Passwords
trashbin
Last changed

maybee you can use this website?
https://www.transifex.com/owncloud_robot/owncloud/
there are a lot of translation

**Comment by fcturner** [comment]
Nice idea, but Transfix costs $19 a month. Really expensive for a small hobby project :rage:

**Comment by Nemofly** [comment]
Oh sorry i do not know it.
Maybe you can ask one who pays it to add your repository? 

Von meinem iPhone gesendet

**Comment by Nemofly** [comment]
maybee you can ask 
owncloud_robot (I Robot)
he has a lot apps in this Group. I translate there a lot of Apps.
It will be nice
