### ISSUE TITLE
Add admin option to copy values with Javascript

### ISSUE THREAD

**Issue by muyiscoi** [fcturner/passwords#75]
This is more of a feature request than an issue. 
Right now, its not very easy to copy a password. You first need to click the "edit" button, then highlight and Ctrl+C or right click and copy.
I suggest that there should be a "copy" button beside the password that appears on hover and automatically copies the selected password into clipboard when clicked, after which I could just go paste it in the appropriate password field.

**Comment by fcturner** [comment]
Many people think your solution might be a security risk.

Besides, it then should be implemented with `document.execCommand('copy')`, and that's only supported on:
  - IE10+
  - Google Chrome 43+ (April 2015): https://developers.google.com/web/updates/2015/04/cut-and-copy-commands?hl=en
  - Mozilla Firefox 41+ (September 2015): https://developer.mozilla.org/en-US/Firefox/Releases/41#Interfaces.2FAPIs.2FDOM
  - Opera 29+ (based on Chromium 42, April 2015): https://dev.opera.com/blog/opera-29/#cut-and-copy-commands

You know what, I will create this as it was asked before. But I will let admins choose to let it be used by adding an option on the admin settings page.

**Comment by muyiscoi** [comment]
That's fine. Looking forward to that!

**Comment by fcturner** [comment]
Auto select with instruction text implemented already, forgot to mention.
Latest release: [v16](https://github.com/fcturner/passwords/releases/tag/16).
