### ISSUE TITLE
Values containing backslash and quotation marks are not supported

### ISSUE THREAD

**Issue by fcturner** [fcturner/passwords#76]
Fix:
Export: `\` -> `\\`
Import: `\\` -> `\`

Export: `"` -> `\"`
Import: `\"` -> `"`

**Comment by fcturner** [comment]
Fixed in master branch. Get the [file here](https://github.com/fcturner/passwords/blob/master/js/script.js) (will be in release 8.0.14 next weekend).

@Yamakasi @IzK666 @muyiscoi

**Comment by fcturner** [comment]
I checked KeePass, it only escapes the `\` and the `"`, so this works. I just tested it with KeePass 2.30, exporting as CSV 1.*. 
This is implemented for all values, as KeePass does this too (website, username, password, notes).

**Comment by Yamakasi** [comment]
OK, what else can we check, other characters ?

**Comment by fcturner** [comment]
No, I think this should be it. The `"` character needs to be escaped because CSV files split values as `"Value1","Value2"`. The `\` character needs to be escaped because [it *is* the escape character](https://en.wikipedia.org/wiki/Escape_character#JavaScript). 

I cannot think of other characters that need escaping. Javascript needs escaping for:
  - `\'` - single quote
  - `\"` - double quote
  - `\\` - backslash
  - `\/` - slash
  - `\n` - new line
  - `\r` - carriage return
  - `\t` - tab
  - `\b` - backspace
  - `\f` - form feed

But for CSV import and export, only the `"` and `\` are used. Single quotes and (forward)slashes don't need escaping (tested that, too).

**Comment by Yamakasi** [comment]
OK, nice, is there some patch I can test ?

**Comment by fcturner** [comment]
Sure, download and test the master: https://github.com/fcturner/passwords/archive/master.zip

**Comment by Yamakasi** [comment]
OK, tried but still the same issue.

I'm confused.

**Comment by Yamakasi** [comment]
OK fixed, when you have comments in Keepass with multiple lines, this goes wrong, now the master branch works.

I'm not 100% sure if it fit my needs, can't we make a version that reads out of kdbx file :) That would be awesome.

**Comment by fcturner** [comment]
Nice research! Exactly what I needed. Now, this means that KeePass notes aren't fully imported if they contain more than one line. That needs a fix: #77. 

KDBX and KDB files cannot be imported, no :cry:
They are encrypted (by a password, file or Windows credentials) and are in fact HEX files. No way of converting that into readable lines. CSV is really our only option.

**Comment by fcturner** [comment]
Fixed as of [8.0.14](https://github.com/fcturner/passwords/releases/tag/8.0.14).
