### ISSUE TITLE
Emptying trash bin not working (Firefox only)

### ISSUE THREAD

**Issue by IzK666** [fcturner/passwords#80]
Hi.
I can't understand why that happens.
If you connect to OC with firefox, the trash bin isn't emptied.

I have added that line before reloading the page and then works fine, but is a <b>very</b> dirty way:
<code>alert("Something");</code>

I have tried to add a delay (with a script I found somewhere), but didn't work. The script stops, but trash isn't emptied.

IzK.

**Comment by IzK666** [comment]
More information:
On opera 12 and Vivaldi (Chrome based) works fine your script.
The error is only on firefox.

**Comment by fcturner** [comment]
Please check v15 :smile:

**Comment by IzK666** [comment]
Still not working.
Sorry.

**Comment by fcturner** [comment]
Fixed as of [v16](https://github.com/fcturner/passwords/releases/tag/16).
