### ISSUE TITLE
"No app name specified"

### ISSUE THREAD

**Issue by border0464111** [fcturner/passwords#87]
Hi, I just installed the app by doing  
`  cd  public_html/apps/

    wget https://github.com/fcturner/passwords/archive/15.zip

    unzip 15.zip

    chown -R www-data:www-data passwords-15`

then iv connected as admin ant tried to enable the app but there was an error message: 
No app name specified

owncloud.log only say : 
`{"reqId":"5yb0brXy6crU79d1RfUE","remoteAddr":"000.000.000.000","app":"core","message":"No app name specified","level":3,"time":"2015-10-15T18:51:41+00:00"}`

**Comment by fcturner** [comment]
Like the readme states:

Download this latest release and copy the folder 'passwords' to /owncloud/apps/ (**remember that the folder must be called 'passwords'**). Login as admin and enable the app.


So: 
`mv passwords-15 passwords'

**Comment by border0464111** [comment]
my bad, sorry. It work now , thx

**Comment by fcturner** [comment]
:+1: :smile:
