### ISSUE TITLE
Changes are not applied

### ISSUE THREAD

**Issue by raptwa** [fcturner/passwords#91]
Changing "Website" and "Full URL" are not stored permanently, when option "Move old value to trashbin" is not enabled.

**Comment by IzK666** [comment]
This issue is exclusive from Firefox.
It only happens if you modify "Full URL" without moving value to trashbin.

**Comment by fcturner** [comment]
Thanks! Will be in next release.

**Comment by fcturner** [comment]
Firefox doesn't seem to like `location.reload(true);` out of the blue... So if preceded by an alert, it should work:
```js
// URL needs to be updated; requires reload of page
if (address != address_old) {
	alert(t('passwords', 'As the URL was changed, this page will now reload.'));
	location.reload(true);
}
```

I still need to test this on different OSes.

**Comment by fcturner** [comment]
Fixed as of [v16](https://github.com/fcturner/passwords/releases/tag/16).
