### ISSUE TITLE
add timeout and demand re-authorization

### ISSUE THREAD

**Issue by paroj** [fcturner/passwords#92]
**usecase:** you left your PC unattended for 15min without a screenlock
**problem:** anyone with physical access can browse to owncloud and view your passwords
**proposed solution:** demand re-authorization when loading the app, add a timeout if app is already open - similarly to what passman does.

**Comment by fcturner** [comment]
I've built a timer. Will be in next version. Thanks for the idea!

But to check for inactivity cannot be done ownCloud wide. I COULD check for the last login time stamp, and log the user off after x minutes, but that would include activities in other apps on the same session cookie. Hmm, still need to think this thru. Great idea though.

**Comment by paroj** [comment]
how about doing following when loading the app:

1. [re-authenticate the user using the external API](https://doc.owncloud.org/server/8.2/developer_manual/core/externalapi.html)
2. if 1. succeeded, send the xhr for the passwords
3. after timeout if X minutes, clear the HTML and return to 1.

probably you would need to make the passwords available over the external API only, so this becomes safe. (an attacker could manually send the XHR for a logged-in user)

**Comment by fcturner** [comment]
Do you know how annoying it is if you login to ownCloud to get a password, and after selecting the app you need to enter your password again? But the biggest problem is that I don't know anything about API's, so I must learn that first. 

Probably the best solution for *you left your PC unattended for 15min without a screenlock* is: **you shouldn't!** With my new timer this is solved your way, but it only runs in the Passwords app. It is a countdown timer, set per user, with valid values ranged 1-3599 seconds, and will reset on every click inside the app.

**Comment by paroj** [comment]
> Do you know how annoying it is if you login to ownCloud to get a password, and after selecting the app you need to enter your password again

as you said, you could check for the login timestamp in this case and do not require the password then. The check would need to happen in the backend, so an attacker could not circumvent the timeout lock.

>  But the biggest problem is that I don't know anything about API's, so I must learn that first.

seems like you just need to register a callback with Owncloud and it will take care of the rest for you.

> Probably the best solution for you left your PC unattended for 15min without a screenlock is: you shouldn't!

this is correct. However I think that a password manager app should protect the passwords as much as possible - especially in real world scenarios.
Note that it is not always as obvious as leaving a screen with you passwords app open: imagine you logged in somewhere to your cloud to just get a file, then closed the tab *without logging out* and went away.
Anybody could now go back to your cloud, open the passwords app and get access to everything.

**Comment by IzK666** [comment]
Just an ideas.
owncloud can be configured to expire the session after X time (by default is 1 day, but the keep alive feature is enabled in order to avoid expire the session).
It should be configured manually by the admin on the server editing the file config/config.php and adding these lines:
'remember_login_cookie_lifetime' =>60 * 60 * 24,
'session_lifetime' => 60,
'session_keepalive' => false,
The time for session is expressed in seconds.

Source: https://doc.owncloud.org/server/8.1/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=session_keepalive

The problem is that once the session is expire, nothing happens until you click something (not javascript calls). Maybe it can be used the variable \OC::$server->getConfig()->getSystemValue('session_lifetime', 60) to get that value. The problem is reading this variable from JS code.

**Comment by fcturner** [comment]
>The problem is that once the session is expire, nothing happens until you click something (not javascript calls). Maybe it can be used the variable \OC::$server->getConfig()->getSystemValue('session_lifetime', 60) to get that value and do a location reload after (Time+1). The problem is reading this variable from JS code.

I solved this. Just set a var to a field and let JS count down (not interactive, just kill session on `t = 0`).

**Comment by fcturner** [comment]
Implemented as of [v16](https://github.com/fcturner/passwords/releases/tag/16).
